name: 'Setup E2E Tests'
description: 'Install Python dependencies and Playwright for E2E testing'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Test Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install httpx pytest pytest-asyncio pytest-playwright reportlab
        npx playwright install chromium --with-deps
