name: 'Setup E2E Tests'
description: 'Install Python dependencies and Playwright for E2E testing'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "tests/e2e/requirements.txt"

    - name: Set up Python
      run: uv python install 3.12
      shell: bash

    - name: Install Test Dependencies
      shell: bash
      run: |
        # Core deps + Playwright + Xdist for parallel execution
        uv pip install httpx pytest pytest-asyncio pytest-playwright pytest-xdist reportlab
        uv run playwright install chromium --with-deps
