name: 'Setup E2E Tests'
description: 'Install Python dependencies and Playwright for E2E testing'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "tests/e2e/requirements.txt"

    - name: Set up Python
      run: uv python install 3.12
      shell: bash

    - name: Install Test Dependencies
      shell: bash
      run: |
        # Create virtual environment and install dependencies
        uv venv
        uv pip install -r tests/e2e/requirements.txt
        
        # Add venv bin to PATH so subsequent steps can use 'pytest' and 'playwright' directly
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        
        # Install playwright browsers
        # Note: We must use the venv's python/playwright explicitly if PATH update hasn't propagated to current shell
        ./.venv/bin/playwright install chromium --with-deps
