"""``reconciliation`` — matching, review consistency, and transfer pairing domain."""

from __future__ import annotations

from src.reconciliation.base import (
    DEFAULT_CONFIG,
    MAX_COMBINATION_CANDIDATES,
    MatchCandidate,
    ReconciliationConfig,
    _candidate_is_better,
    entry_bank_side_amount,
    entry_total_amount,
    is_entry_balanced,
    load_reconciliation_config,
)
from src.reconciliation.data import ReconciliationStats, get_reconciliation_stats
from src.reconciliation.extension.fx_transfer import (
    DEFAULT_RATE_TOLERANCE,
    DEFAULT_TIME_WINDOW,
    FxTransferError,
    TransferLeg,
    classify_internal_transfer,
    pair_fx_legs,
)
from src.reconciliation.extension.fx_transfer_discovery import discover_fx_conversions
from src.reconciliation.extension.matching import (
    _find_many_to_one_candidates,
    _find_normal_candidates,
    _find_transfer_candidates,
    _get_existing_active_match,
    _get_pending_layer2_transactions,
    _within_combination_tolerance,
    auto_accept,
    build_many_to_one_groups,
    calculate_match_score,
    execute_matching,
    find_candidates,
    prune_candidates,
    sync_reconciliation_match_journal_entry_links,
)
from src.reconciliation.extension.scoring import (
    ai_semantic_score,
    extract_merchant_tokens,
    is_cross_period,
    normalize_text,
    score_amount,
    score_business_logic,
    score_date,
    score_description,
    score_pattern,
    weighted_total,
)

__all__ = [
    "DEFAULT_CONFIG",
    "MAX_COMBINATION_CANDIDATES",
    "MatchCandidate",
    "ReconciliationConfig",
    "ReconciliationStats",
    "DEFAULT_RATE_TOLERANCE",
    "DEFAULT_TIME_WINDOW",
    "FxTransferError",
    "TransferLeg",
    "classify_internal_transfer",
    "discover_fx_conversions",
    "pair_fx_legs",
    "_candidate_is_better",
    "_find_many_to_one_candidates",
    "_find_normal_candidates",
    "_find_transfer_candidates",
    "_get_existing_active_match",
    "_get_pending_layer2_transactions",
    "_within_combination_tolerance",
    "ai_semantic_score",
    "auto_accept",
    "build_many_to_one_groups",
    "calculate_match_score",
    "entry_bank_side_amount",
    "entry_total_amount",
    "execute_matching",
    "extract_merchant_tokens",
    "find_candidates",
    "get_reconciliation_stats",
    "is_cross_period",
    "is_entry_balanced",
    "load_reconciliation_config",
    "normalize_text",
    "prune_candidates",
    "score_amount",
    "score_business_logic",
    "score_date",
    "score_description",
    "score_pattern",
    "sync_reconciliation_match_journal_entry_links",
    "weighted_total",
]
