"""``reconciliation`` — matching, review consistency, and transfer pairing domain."""

from __future__ import annotations

from src.reconciliation.base import (
    DEFAULT_CONFIG,
    MAX_COMBINATION_CANDIDATES,
    RECONCILIATION_SEMANTIC_PROMPT,
    AmountMismatchError,
    CheckResolutionAction,
    ConsistencyCheckNotFoundError,
    EntryCreationError,
    InvalidCheckActionError,
    MatchCandidate,
    MatchNotFoundError,
    ReconciliationConfig,
    ReconciliationError,
    _candidate_is_better,
    build_reconciliation_prompt,
    entry_bank_side_amount,
    entry_total_amount,
    is_entry_balanced,
    load_reconciliation_config,
)
from src.reconciliation.data import ReconciliationStats, get_reconciliation_stats
from src.reconciliation.extension.anomaly import detect_anomalies
from src.reconciliation.extension.consistency_checks import (
    has_unresolved_checks,
    list_checks,
    resolve_check,
    run_all_consistency_checks,
)
from src.reconciliation.extension.fx_transfer import (
    DEFAULT_RATE_TOLERANCE,
    DEFAULT_TIME_WINDOW,
    FxTransferError,
    TransferLeg,
    classify_internal_transfer,
    pair_fx_legs,
)
from src.reconciliation.extension.fx_transfer_discovery import discover_fx_conversions
from src.reconciliation.extension.matching import (
    MatchingContext,
    _find_many_to_one_candidates,
    _find_normal_candidates,
    _find_transfer_candidates,
    _get_existing_active_match,
    _get_pending_layer2_transactions,
    _within_combination_tolerance,
    accepted_transfer_txn_ids,
    auto_accept,
    build_many_to_one_groups,
    calculate_match_score,
    execute_matching,
    find_candidates,
    prune_candidates,
    score_group,
    score_single,
    sync_reconciliation_match_journal_entry_links,
)
from src.reconciliation.extension.review_queue import (
    accept_match,
    batch_accept,
    get_pending_items,
    get_stage2_queue,
    reject_match,
)
from src.reconciliation.extension.scoring import (
    extract_merchant_tokens,
    is_cross_period,
    normalize_text,
    score_amount,
    score_business_logic,
    score_date,
    score_description,
    score_pattern,
    weighted_total,
)

# ORM models owned by this package (moved from src/models, #1675); imported
# eagerly so importing the package registers the mappers on Base.metadata.
from src.reconciliation.orm.consistency_check import CheckStatus, CheckType, ConsistencyCheck
from src.reconciliation.orm.reconciliation import (
    ReconciliationMatch,
    ReconciliationMatchJournalEntry,
    ReconciliationStatus,
)

__all__ = [
    "AmountMismatchError",
    "CheckResolutionAction",
    "CheckStatus",
    "CheckType",
    "ConsistencyCheck",
    "ConsistencyCheckNotFoundError",
    "DEFAULT_CONFIG",
    "DEFAULT_RATE_TOLERANCE",
    "DEFAULT_TIME_WINDOW",
    "EntryCreationError",
    "FxTransferError",
    "InvalidCheckActionError",
    "MAX_COMBINATION_CANDIDATES",
    "MatchCandidate",
    "MatchNotFoundError",
    "MatchingContext",
    "RECONCILIATION_SEMANTIC_PROMPT",
    "ReconciliationConfig",
    "ReconciliationError",
    "ReconciliationMatch",
    "ReconciliationMatchJournalEntry",
    "ReconciliationStats",
    "ReconciliationStatus",
    "TransferLeg",
    "_candidate_is_better",
    "_find_many_to_one_candidates",
    "_find_normal_candidates",
    "_find_transfer_candidates",
    "_get_existing_active_match",
    "_get_pending_layer2_transactions",
    "_within_combination_tolerance",
    "accept_match",
    "accepted_transfer_txn_ids",
    "auto_accept",
    "batch_accept",
    "build_many_to_one_groups",
    "build_reconciliation_prompt",
    "calculate_match_score",
    "classify_internal_transfer",
    "detect_anomalies",
    "discover_fx_conversions",
    "entry_bank_side_amount",
    "entry_total_amount",
    "execute_matching",
    "extract_merchant_tokens",
    "find_candidates",
    "get_pending_items",
    "get_reconciliation_stats",
    "get_stage2_queue",
    "has_unresolved_checks",
    "is_cross_period",
    "is_entry_balanced",
    "list_checks",
    "load_reconciliation_config",
    "normalize_text",
    "pair_fx_legs",
    "prune_candidates",
    "reject_match",
    "resolve_check",
    "run_all_consistency_checks",
    "score_amount",
    "score_business_logic",
    "score_date",
    "score_description",
    "score_group",
    "score_single",
    "score_pattern",
    "sync_reconciliation_match_journal_entry_links",
    "weighted_total",
]
