from __future__ import annotations

import sys
from types import ModuleType

from common.platform import generate_api_reference as gar


def test_render_openapi_reference_uses_openapi_shape() -> None:
    """AC8.13.53: generated API reference renders OpenAPI-owned contracts."""
    schema = {
        "info": {"title": "Demo API", "version": "1.2.3"},
        "paths": {
            "/journal-entries": {
                "get": {
                    "tags": ["journal-entries"],
                    "summary": "List Journal Entries",
                    "security": [{"OAuth2PasswordBearer": []}],
                    "parameters": [
                        {
                            "name": "status_filter",
                            "in": "query",
                            "required": False,
                            "schema": {"type": "string"},
                        }
                    ],
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/JournalEntryList"
                                    }
                                }
                            }
                        }
                    },
                }
            },
            "/reconciliation/runs": {
                "post": {
                    "tags": ["reconciliation"],
                    "summary": "Run Reconciliation",
                    "security": [],
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ReconciliationRunRequest"
                                }
                            }
                        }
                    },
                    "responses": {
                        "200": {"content": {}},
                        "404": {
                            "content": {
                                "application/json": {
                                    "schema": {"type": "object"},
                                }
                            }
                        },
                    },
                }
            },
            "/schemas": {
                "get": {
                    "tags": ["untagged"],
                    "summary": "Schema Samples",
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "items": {
                                            "anyOf": [
                                                {"$ref": "#/components/schemas/A"},
                                                {
                                                    "allOf": [
                                                        {"type": "string"},
                                                        {"enum": ["x"]},
                                                    ]
                                                },
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                }
            },
        },
        "components": {
            "schemas": {"JournalEntryList": {}, "ReconciliationRunRequest": {}}
        },
    }

    rendered = gar.render_openapi_reference(schema)

    assert "API title: `Demo API`" in rendered
    assert "| `GET` | `/journal-entries` | yes | `status_filter` (query)" in rendered
    assert "`ReconciliationRunRequest`" in rendered
    assert "array[`A` \\| string + enum]" in rendered
    assert "PUT /api/journal-entries" not in rendered


def test_checked_in_api_reference_is_generated_inventory() -> None:
    """AC8.13.53: checked-in API reference stays generated and drift-free."""
    text = gar.OUTPUT_PATH.read_text(encoding="utf-8")

    assert "Generated by `python tools/generate_api_reference.py`" in text
    assert "| `POST` | `/reconciliation/runs`" in text
    assert "`ReconciliationRunRequest`" in text
    assert "`account_id` (query)" not in text
    assert (
        "`start_date` (query)"
        not in text.split("`/reconciliation/runs`", 1)[1].split("\n", 1)[0]
    )
    assert "`PUT` | `/journal-entries/{entry_id}`" not in text


def test_load_openapi_imports_backend_app(monkeypatch, tmp_path) -> None:
    """AC8.13.53: OpenAPI loading imports the backend app from backend root."""
    fake_src = ModuleType("src")
    fake_main = ModuleType("src.main")

    class FakeApp:
        def openapi(self) -> dict[str, object]:
            return {"paths": {}}

    fake_main.app = FakeApp()
    monkeypatch.setattr(gar, "BACKEND_ROOT", tmp_path)
    monkeypatch.setitem(sys.modules, "src", fake_src)
    monkeypatch.setitem(sys.modules, "src.main", fake_main)
    while str(tmp_path) in sys.path:
        sys.path.remove(str(tmp_path))

    assert gar._load_openapi() == {"paths": {}}
    assert str(tmp_path) in sys.path


def test_main_writes_generated_output(monkeypatch, tmp_path) -> None:
    """AC8.13.53: generator write mode updates the requested output path."""
    output = tmp_path / "nested" / "api.md"
    monkeypatch.setattr(gar, "generate", lambda: "# API\n")

    assert gar.main(["--output", str(output)]) == 0
    assert output.read_text(encoding="utf-8") == "# API\n"


def test_main_check_passes_when_output_is_current(monkeypatch, tmp_path) -> None:
    """AC8.13.53: --check passes when generated API docs are current."""
    output = tmp_path / "api.md"
    output.write_text("# API\n", encoding="utf-8")
    monkeypatch.setattr(gar, "generate", lambda: "# API\n")

    assert gar.main(["--output", str(output), "--check"]) == 0


def test_main_check_fails_when_output_is_missing(monkeypatch, tmp_path, capsys) -> None:
    """AC8.13.53: --check fails closed when generated API docs are missing."""
    output = tmp_path / "missing.md"
    monkeypatch.setattr(gar, "generate", lambda: "# API\n")

    assert gar.main(["--output", str(output), "--check"]) == 1

    captured = capsys.readouterr()
    assert "generated API reference is missing" in captured.err


def test_main_check_fails_when_output_is_stale(monkeypatch, tmp_path, capsys) -> None:
    """AC8.13.53: --check reports a diff when generated API docs are stale."""
    output = tmp_path / "api.md"
    output.write_text("# Old\n", encoding="utf-8")
    monkeypatch.setattr(gar, "generate", lambda: "# New\n")

    assert gar.main(["--output", str(output), "--check"]) == 1

    captured = capsys.readouterr()
    assert "generated API reference is stale" in captured.err
    assert "---" in captured.err
    assert "+++" in captured.err
