from __future__ import annotations

from common.meta.extension import generate_db_schema_reference as gdsr
from sqlalchemy import (
    CheckConstraint,
    Column,
    Enum,
    ForeignKey,
    Integer,
    MetaData,
    String,
    Table,
)


def test_AC14_1_17_render_db_schema_reference_uses_sqlalchemy_metadata() -> None:
    """AC-meta.generated-refs.1: generated DB reference renders SQLAlchemy-owned contracts."""
    metadata = MetaData()
    Table(
        "users",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("email", String(255), nullable=False, unique=True, index=True),
    )
    Table(
        "journal_entries",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("user_id", Integer, ForeignKey("users.id"), nullable=False, index=True),
        Column("status", Enum("draft", "posted", name="entry_status"), nullable=False),
        CheckConstraint("status <> ''", name="ck_journal_entries_status_non_empty"),
    )

    rendered = gdsr.render_db_schema_reference(metadata)

    assert "Table count: `2`" in rendered
    assert "Column count: `5`" in rendered
    assert "Enum type count: `1`" in rendered
    assert "| `journal_entries` | 3 | `id` | 1 | 1 |" in rendered
    assert "| `status` | `entry_status` | no | no | - | - |" in rendered
    assert (
        "| `entry_status` | yes | `draft`, `posted` | `journal_entries.status` |"
        in rendered
    )
    assert "| `journal_entries.user_id` | `users.id` |" in rendered
    assert "ck_journal_entries_status_non_empty" in rendered


def test_AC14_1_17_db_schema_reference_is_build_time_generated_inventory() -> None:
    """AC14.1.17: DB reference is generated from metadata, not hand-maintained."""
    text = gdsr.generate()

    assert "Generated by `python tools/generate_db_schema_reference.py`" in text
    assert "Do not edit by hand" in text
    assert "| `accounts` |" in text
    assert "| `journal_entries` |" in text
    assert "`account_type_enum`" in text
    assert "`journal_entry_status_enum`" in text
    assert "## Foreign Keys" in text


def test_AC14_1_17_db_schema_reference_is_gitignored_and_mkdocs_generated() -> None:
    """AC14.1.17: generated DB inventory is built for MkDocs, not stored in git."""
    gitignore = (gdsr.REPO_ROOT / ".gitignore").read_text(encoding="utf-8")
    mkdocs = (gdsr.REPO_ROOT / "mkdocs.yml").read_text(encoding="utf-8")
    hook = (gdsr.REPO_ROOT / "docs" / "hooks.py").read_text(encoding="utf-8")

    assert "docs/reference/db-schema.md" in gitignore
    assert "hooks:" in mkdocs
    assert "docs/hooks.py" in mkdocs
    assert "generate_db_schema_reference.py" in hook


def test_AC14_1_17_load_metadata_imports_backend_models_without_connecting() -> None:
    """AC14.1.17: generation loads model metadata without requiring a DB connection."""
    metadata = gdsr._load_metadata()

    assert "accounts" in metadata.tables
    assert "journal_entries" in metadata.tables
    assert "statement_summaries" in metadata.tables


def test_main_writes_generated_db_schema_output(monkeypatch, tmp_path) -> None:
    """AC14.1.17: generator write mode updates the requested output path."""
    output = tmp_path / "nested" / "db-schema.md"
    monkeypatch.setattr(gdsr, "generate", lambda: "# DB\n")

    assert gdsr.main(["--output", str(output)]) == 0
    assert output.read_text(encoding="utf-8") == "# DB\n"


def test_main_check_passes_when_db_schema_output_is_current(
    monkeypatch, tmp_path
) -> None:
    """AC14.1.17: --check passes when generated DB docs are current."""
    output = tmp_path / "db-schema.md"
    output.write_text("# DB\n", encoding="utf-8")
    monkeypatch.setattr(gdsr, "generate", lambda: "# DB\n")

    assert gdsr.main(["--output", str(output), "--check"]) == 0


def test_main_check_fails_when_db_schema_output_is_missing(
    monkeypatch, tmp_path, capsys
) -> None:
    """AC14.1.17: --check fails closed when generated DB docs are missing."""
    output = tmp_path / "missing.md"
    monkeypatch.setattr(gdsr, "generate", lambda: "# DB\n")

    assert gdsr.main(["--output", str(output), "--check"]) == 1

    captured = capsys.readouterr()
    assert "generated DB schema reference is missing" in captured.err


def test_main_check_fails_when_db_schema_output_is_stale(
    monkeypatch, tmp_path, capsys
) -> None:
    """AC14.1.17: --check reports a diff when generated DB docs are stale."""
    output = tmp_path / "db-schema.md"
    output.write_text("# Old\n", encoding="utf-8")
    monkeypatch.setattr(gdsr, "generate", lambda: "# New\n")

    assert gdsr.main(["--output", str(output), "--check"]) == 1

    captured = capsys.readouterr()
    assert "generated DB schema reference is stale" in captured.err
    assert "---" in captured.err
    assert "+++" in captured.err
