#!/usr/bin/env python3
"""Generate ``docs/ssot/critical-proof-matrix.yaml`` from co-located declarations.

The ``proofs:`` section of the matrix is a DERIVED index. Its source of truth is
the ``@ac_proof(...)`` decorator co-located on each critical-proof test (see
:mod:`common.testing.ac_proof`). This generator statically scans the test tree
for those decorators — mirroring the AST style of
``common.ssot.check_critical_proof_matrix`` and the generated-artifact contract
of ``common.ssot.generate_ac_registry`` — and emits the matrix.

The ``outcomes:`` section is the README/EPIC macro-outcome contract, not a
per-test fact, so it is kept as a small hand-maintained source file
(``docs/ssot/critical-proof-outcomes.yaml``) and merged in verbatim. Outcomes
rarely change and are NOT the merge-train false-sharing hotspot; the per-AC
``proofs[]`` appends were.

``--check`` exits non-zero when the checked-in YAML differs from a fresh
generation, exactly like ``tools/generate_ac_registry.py --check``.
"""

from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MATRIX = REPO_ROOT / "docs" / "ssot" / "critical-proof-matrix.yaml"
DEFAULT_OUTCOMES = REPO_ROOT / "docs" / "ssot" / "critical-proof-outcomes.yaml"

# Test roots scanned for @ac_proof declarations. These mirror the product test
# surfaces the matrix already accepts (see check_critical_proof_matrix roots),
# plus the integration/api PR-tier mirrors.
SCAN_ROOTS = (
    "tests/e2e",
    "apps/backend/tests",
    "apps/frontend/src",
)

DECORATOR_NAME = "ac_proof"

# Ordered keys emitted per proof, matching the historical YAML field order so the
# generated artifact is stable and diff-friendly.
_PROOF_KEY_ORDER = (
    "id",
    "scope",
    "ci_tier",
    "trust_mode",
    "source_classes",
    "mirror_proof_id",
    "issue",
    "file",
    "test",
    "required_markers",
    "ac_ids",
)

_HEADER = (
    "# DO NOT edit this file manually - it is generated.\n"
    "# Source of truth:\n"
    "#   proofs   -> @ac_proof(...) decorators on the tests (common/testing/ac_proof.py)\n"
    "#   outcomes -> docs/ssot/critical-proof-outcomes.yaml\n"
    "# Regenerate: python tools/generate_critical_proof_matrix.py\n"
    "# Verify:     python tools/generate_critical_proof_matrix.py --check\n"
)


class GeneratorError(RuntimeError):
    """Raised when a declaration cannot be statically converted to a proof."""


@dataclass
class CollectedProof:
    proof_id: str
    file: str
    test: str
    fields: dict[str, Any]


def _rel(path: Path, repo_root: Path) -> str:
    try:
        return path.relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def _literal(node: ast.AST, *, where: str) -> Any:
    """Evaluate one decorator argument as a plain literal.

    Lists/tuples become lists. Anything non-literal (a name, call, f-string)
    is rejected so the generated artifact stays a faithful static projection.
    """
    try:
        value = ast.literal_eval(node)
    except (ValueError, SyntaxError) as exc:
        raise GeneratorError(
            f"{where}: @ac_proof arguments must be plain literals"
        ) from exc
    if isinstance(value, tuple):
        return list(value)
    return value


def _decorator_proof_call(node: ast.AST) -> ast.Call | None:
    """Return the ``ac_proof(...)`` call decorating *node*, if any."""
    for decorator in getattr(node, "decorator_list", []):
        if not isinstance(decorator, ast.Call):
            continue
        func = decorator.func
        name = (
            func.attr
            if isinstance(func, ast.Attribute)
            else func.id
            if isinstance(func, ast.Name)
            else None
        )
        if name == DECORATOR_NAME:
            return decorator
    return None


def _collect_from_file(path: Path, repo_root: Path) -> list[CollectedProof]:
    module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    rel_file = _rel(path, repo_root)
    collected: list[CollectedProof] = []
    for node in ast.walk(module):
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        call = _decorator_proof_call(node)
        if call is None:
            continue
        where = f"{rel_file}::{node.name}"

        kwargs: dict[str, Any] = {}
        for keyword in call.keywords:
            if keyword.arg is None:
                raise GeneratorError(f"{where}: @ac_proof does not accept **kwargs")
            kwargs[keyword.arg] = _literal(keyword.value, where=where)

        if call.args:
            proof_id = _literal(call.args[0], where=where)
        else:
            proof_id = kwargs.pop("proof_id", None)
        if not isinstance(proof_id, str) or not proof_id:
            raise GeneratorError(f"{where}: @ac_proof requires a string proof id")

        ac_ids = kwargs.get("ac_ids")
        if not isinstance(ac_ids, list) or not ac_ids:
            raise GeneratorError(f"{where}: @ac_proof requires a non-empty ac_ids list")

        fields: dict[str, Any] = {
            "id": proof_id,
            "scope": kwargs.get("scope", "behavioral"),
            "ci_tier": kwargs.get("ci_tier", "post_merge_environment"),
            "file": rel_file,
            "test": node.name,
            "ac_ids": [str(ac_id) for ac_id in ac_ids],
        }
        for optional in ("trust_mode", "mirror_proof_id", "issue"):
            value = kwargs.get(optional)
            if value:
                fields[optional] = str(value)
        for list_key in ("source_classes", "required_markers"):
            value = kwargs.get(list_key)
            if value:
                fields[list_key] = [str(item) for item in value]

        collected.append(
            CollectedProof(
                proof_id=proof_id,
                file=rel_file,
                test=node.name,
                fields=fields,
            )
        )
    return collected


def collect_proofs(repo_root: Path) -> list[CollectedProof]:
    """Statically collect every ``@ac_proof`` declaration under the scan roots."""
    proofs: list[CollectedProof] = []
    for root in SCAN_ROOTS:
        root_path = repo_root / root
        if not root_path.exists():
            continue
        for path in sorted(root_path.rglob("*.py")):
            proofs.extend(_collect_from_file(path, repo_root))
    return proofs


def _ordered_proof(fields: dict[str, Any]) -> dict[str, Any]:
    ordered = {key: fields[key] for key in _PROOF_KEY_ORDER if key in fields}
    # Defensive: surface any unexpected keys deterministically at the end.
    for key, value in fields.items():
        if key not in ordered:
            ordered[key] = value
    return ordered


def build_matrix(repo_root: Path, outcomes_path: Path) -> dict[str, Any]:
    """Return the full matrix payload (outcomes source + generated proofs)."""
    outcomes_doc = yaml.safe_load(outcomes_path.read_text(encoding="utf-8"))
    if not isinstance(outcomes_doc, dict):
        raise GeneratorError(f"{outcomes_path} must contain a YAML mapping")

    proofs = collect_proofs(repo_root)
    seen: dict[str, str] = {}
    duplicates: list[str] = []
    for proof in proofs:
        prior = seen.get(proof.proof_id)
        if prior is not None:
            duplicates.append(
                f"{proof.proof_id} ({prior} and {proof.file}::{proof.test})"
            )
        seen[proof.proof_id] = f"{proof.file}::{proof.test}"
    if duplicates:
        raise GeneratorError(
            "duplicate proof ids across @ac_proof declarations: "
            + "; ".join(sorted(duplicates))
        )

    proofs.sort(key=lambda item: item.proof_id)
    payload: dict[str, Any] = {
        "version": str(outcomes_doc.get("version", "1.0")),
    }
    if "description" in outcomes_doc:
        payload["description"] = outcomes_doc["description"]
    payload["outcomes"] = outcomes_doc.get("outcomes", [])
    payload["proofs"] = [_ordered_proof(proof.fields) for proof in proofs]
    return payload


def render_matrix(payload: dict[str, Any]) -> str:
    class IndentedDumper(yaml.SafeDumper):
        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)

    rendered = yaml.dump(
        payload,
        Dumper=IndentedDumper,
        sort_keys=False,
        allow_unicode=False,
        width=4096,
        default_flow_style=False,
    )
    return _HEADER + rendered


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the critical proof matrix from co-located @ac_proof declarations."
    )
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--matrix", type=Path, default=DEFAULT_MATRIX)
    parser.add_argument("--outcomes", type=Path, default=DEFAULT_OUTCOMES)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the checked-in matrix differs from a fresh generation.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args([] if argv is None else argv)
    repo_root = args.repo_root.resolve()
    matrix_path = args.matrix if args.matrix.is_absolute() else repo_root / args.matrix
    outcomes_path = (
        args.outcomes if args.outcomes.is_absolute() else repo_root / args.outcomes
    )

    try:
        payload = build_matrix(repo_root, outcomes_path)
    except GeneratorError as exc:
        print(f"::error title=Critical proof matrix generator::{exc}", file=sys.stderr)
        return 1

    rendered = render_matrix(payload)

    if args.check:
        current = (
            matrix_path.read_text(encoding="utf-8") if matrix_path.exists() else ""
        )
        if current != rendered:
            print(
                "::error title=Critical proof matrix generator::"
                f"{_rel(matrix_path, repo_root)} is out of date.\n"
                "  Run: python tools/generate_critical_proof_matrix.py",
                file=sys.stderr,
            )
            return 1
        print(
            "OK: critical proof matrix matches co-located @ac_proof declarations "
            f"({len(payload['proofs'])} proof path(s))."
        )
        return 0

    matrix_path.parent.mkdir(parents=True, exist_ok=True)
    matrix_path.write_text(rendered, encoding="utf-8")
    print(
        f"Wrote {matrix_path} ({len(payload['proofs'])} proof path(s) "
        "from @ac_proof declarations)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
