#!/usr/bin/env python3
"""Build the critical-proof matrix payload from co-located declarations.

This module is a LIBRARY for the one AC-keyed graph, not a CLI gate. The
``proofs:`` section of the matrix is a DERIVED view whose source of truth is the
``@ac_proof(...)`` decorator co-located on each critical-proof test (see
:mod:`common.testing.ac_proof`). ``collect_proofs`` statically scans the test
tree for those decorators (mirroring the AST style of
``common.ssot.check_critical_proof_matrix``); ``build_matrix_from_graph`` reuses
the proofs the single :class:`~common.ssot.ac_graph.AcGraph` already collected.

The ``outcomes:`` section is the README/EPIC macro-outcome contract, not a
per-test fact, so it is kept as a small hand-maintained source file
(``docs/ssot/critical-proof-outcomes.yaml``) and merged in verbatim.

The matrix is a derived view of the one AC-keyed graph and is NO LONGER
committed-materialized (there is no checked-in ``critical-proof-matrix.yaml`` to
byte-compare against). Full cross-source consistency is gated by the single entry
point ``tools/check_ac_index.py``; this module also exposes a thin ``main()`` that renders the matrix to stdout on demand (the matrix is never committed).
The consumers are ``check_critical_proof_matrix`` (``build_matrix_payload``),
``ac_graph`` (``collect_proofs``), ``staging_ai_ocr_gate_contract``
(``build_matrix_from_graph``), and the matrix unit tests.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]

# Test roots scanned for @ac_proof declarations. These mirror the product test
# surfaces the matrix already accepts (see check_critical_proof_matrix roots),
# plus the integration/api PR-tier mirrors.
SCAN_ROOTS = (
    "tests/e2e",
    "apps/backend/tests",
    "apps/frontend/src",
)

DECORATOR_NAME = "ac_proof"

# Ordered keys emitted per proof, matching the historical YAML field order so the
# generated artifact is stable and diff-friendly.
_PROOF_KEY_ORDER = (
    "id",
    "scope",
    "ci_tier",
    "trust_mode",
    "source_classes",
    "mirror_proof_id",
    "issue",
    "file",
    "test",
    "required_markers",
    "ac_ids",
)

_HEADER = (
    "# DO NOT edit this file manually - it is a derived view, never committed.\n"
    "# Source of truth:\n"
    "#   proofs   -> @ac_proof(...) decorators on the tests (common/testing/ac_proof.py)\n"
    "#   outcomes -> docs/ssot/critical-proof-outcomes.yaml\n"
    "# Consistency gate: python tools/check_ac_index.py\n"
)


class GeneratorError(RuntimeError):
    """Raised when a declaration cannot be statically converted to a proof."""


@dataclass
class CollectedProof:
    proof_id: str
    file: str
    test: str
    fields: dict[str, Any]


def _rel(path: Path, repo_root: Path) -> str:
    try:
        return path.relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def _literal(node: ast.AST, *, where: str) -> Any:
    """Evaluate one decorator argument as a plain literal.

    Lists/tuples become lists. Anything non-literal (a name, call, f-string)
    is rejected so the generated artifact stays a faithful static projection.
    """
    try:
        value = ast.literal_eval(node)
    except (ValueError, SyntaxError) as exc:
        raise GeneratorError(f"{where}: @ac_proof arguments must be plain literals") from exc
    if isinstance(value, tuple):
        return list(value)
    return value


def _decorator_proof_call(node: ast.AST) -> ast.Call | None:
    """Return the ``ac_proof(...)`` call decorating *node*, if any."""
    for decorator in getattr(node, "decorator_list", []):
        if not isinstance(decorator, ast.Call):
            continue
        func = decorator.func
        name = func.attr if isinstance(func, ast.Attribute) else func.id if isinstance(func, ast.Name) else None
        if name == DECORATOR_NAME:
            return decorator
    return None


def _collect_from_file(path: Path, repo_root: Path) -> list[CollectedProof]:
    module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    rel_file = _rel(path, repo_root)
    collected: list[CollectedProof] = []
    for node in ast.walk(module):
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        call = _decorator_proof_call(node)
        if call is None:
            continue
        where = f"{rel_file}::{node.name}"

        kwargs: dict[str, Any] = {}
        for keyword in call.keywords:
            if keyword.arg is None:
                raise GeneratorError(f"{where}: @ac_proof does not accept **kwargs")
            kwargs[keyword.arg] = _literal(keyword.value, where=where)

        if call.args:
            proof_id = _literal(call.args[0], where=where)
        else:
            proof_id = kwargs.pop("proof_id", None)
        if not isinstance(proof_id, str) or not proof_id:
            raise GeneratorError(f"{where}: @ac_proof requires a string proof id")

        ac_ids = kwargs.get("ac_ids")
        if not isinstance(ac_ids, list) or not ac_ids:
            raise GeneratorError(f"{where}: @ac_proof requires a non-empty ac_ids list")

        fields: dict[str, Any] = {
            "id": proof_id,
            "scope": kwargs.get("scope", "behavioral"),
            "ci_tier": kwargs.get("ci_tier", "post_merge_environment"),
            "file": rel_file,
            "test": node.name,
            "ac_ids": [str(ac_id) for ac_id in ac_ids],
        }
        for optional in ("trust_mode", "mirror_proof_id", "issue"):
            value = kwargs.get(optional)
            if value:
                fields[optional] = str(value)
        for list_key in ("source_classes", "required_markers"):
            value = kwargs.get(list_key)
            if value:
                fields[list_key] = [str(item) for item in value]

        collected.append(
            CollectedProof(
                proof_id=proof_id,
                file=rel_file,
                test=node.name,
                fields=fields,
            )
        )
    return collected


def collect_proofs(repo_root: Path) -> list[CollectedProof]:
    """Statically collect every ``@ac_proof`` declaration under the scan roots."""
    proofs: list[CollectedProof] = []
    for root in SCAN_ROOTS:
        root_path = repo_root / root
        if not root_path.exists():
            continue
        for path in sorted(root_path.rglob("*.py")):
            proofs.extend(_collect_from_file(path, repo_root))
    return proofs


def _ordered_proof(fields: dict[str, Any]) -> dict[str, Any]:
    ordered = {key: fields[key] for key in _PROOF_KEY_ORDER if key in fields}
    # Defensive: surface any unexpected keys deterministically at the end.
    for key, value in fields.items():
        if key not in ordered:
            ordered[key] = value
    return ordered


def _matrix_payload(outcomes_doc: dict[str, Any], proofs: list[CollectedProof]) -> dict[str, Any]:
    """Assemble the matrix payload from an outcomes source doc + collected proofs.

    Drives ``build_matrix_from_graph`` (which reuses the single :class:`AcGraph`
    scan), producing the ``{version, description?, outcomes, proofs}`` shape the
    validator consumes.
    """
    seen: dict[str, str] = {}
    duplicates: list[str] = []
    for proof in proofs:
        prior = seen.get(proof.proof_id)
        if prior is not None:
            duplicates.append(f"{proof.proof_id} ({prior} and {proof.file}::{proof.test})")
        seen[proof.proof_id] = f"{proof.file}::{proof.test}"
    if duplicates:
        raise GeneratorError("duplicate proof ids across @ac_proof declarations: " + "; ".join(sorted(duplicates)))

    ordered = sorted(proofs, key=lambda item: item.proof_id)
    payload: dict[str, Any] = {
        "version": str(outcomes_doc.get("version", "1.0")),
    }
    if "description" in outcomes_doc:
        payload["description"] = outcomes_doc["description"]
    payload["outcomes"] = outcomes_doc.get("outcomes", [])
    payload["proofs"] = [_ordered_proof(proof.fields) for proof in ordered]
    return payload


def build_matrix_from_graph(graph: Any) -> dict[str, Any]:
    """Return the matrix payload from a pre-built ``common.ssot.ac_graph.AcGraph``.

    The de-materialized projection: instead of re-scanning the test tree, reuse
    the proofs and outcomes the single AC graph already collected.
    """
    proofs = [
        CollectedProof(
            proof_id=edge.proof_id,
            file=edge.file,
            test=edge.test,
            fields=edge.fields,
        )
        for edge in graph.proofs
    ]
    return _matrix_payload(graph.outcomes_doc, proofs)


def render_matrix(payload: dict[str, Any]) -> str:
    class IndentedDumper(yaml.SafeDumper):
        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)

    rendered = yaml.dump(
        payload,
        Dumper=IndentedDumper,
        sort_keys=False,
        allow_unicode=False,
        width=4096,
        default_flow_style=False,
    )
    return _HEADER + rendered


def main(argv: list[str] | None = None) -> int:
    """Render the derived critical-proof matrix to stdout on demand.

    The matrix is NOT committed; this is the human-facing way to view it. Full
    cross-source consistency is gated by ``tools/check_ac_index.py``.
    """
    import argparse
    import sys

    from common.ssot.ac_graph import build_ac_graph

    parser = argparse.ArgumentParser(
        description="Render the derived critical-proof matrix on demand (never committed)."
    )
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    args = parser.parse_args([] if argv is None else argv)
    graph = build_ac_graph(repo_root=args.repo_root.resolve())
    sys.stdout.write(render_matrix(build_matrix_from_graph(graph)))
    return 0


if __name__ == "__main__":
    import sys as _sys

    raise SystemExit(main(_sys.argv[1:]))
