"""Generate the static API reference from FastAPI OpenAPI.

The runtime OpenAPI document is the API contract. This module emits a compact
MkDocs page that is useful for navigation without copying request/response
field definitions into hand-maintained prose.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
BACKEND_ROOT = REPO_ROOT / "apps" / "backend"
OUTPUT_PATH = REPO_ROOT / "docs" / "reference" / "api.md"


HTTP_METHODS = ("get", "post", "put", "patch", "delete", "options", "head")


def _load_openapi() -> dict[str, Any]:
    if str(BACKEND_ROOT) not in sys.path:
        sys.path.insert(0, str(BACKEND_ROOT))
    from src.main import app  # noqa: PLC0415

    return app.openapi()


def _schema_name(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "-"
    if "$ref" in schema:
        return f"`{schema['$ref'].rsplit('/', 1)[-1]}`"
    if "anyOf" in schema:
        return " | ".join(_schema_name(item) for item in schema["anyOf"])
    if "allOf" in schema:
        return " + ".join(_schema_name(item) for item in schema["allOf"])
    if "items" in schema:
        return f"array[{_schema_name(schema['items'])}]"
    if "enum" in schema:
        return "enum"
    schema_type = schema.get("type")
    return str(schema_type) if schema_type else "-"


def _request_schema(operation: dict[str, Any]) -> str:
    request_body = operation.get("requestBody") or {}
    content = request_body.get("content") or {}
    json_content = content.get("application/json") or next(iter(content.values()), {})
    return _schema_name(json_content.get("schema"))


def _response_schemas(operation: dict[str, Any]) -> str:
    responses = operation.get("responses") or {}
    success: list[str] = []
    for status_code, response in sorted(responses.items()):
        if not str(status_code).startswith(("2", "3")):
            continue
        content = response.get("content") or {}
        json_content = content.get("application/json") or next(
            iter(content.values()), {}
        )
        schema = _schema_name(json_content.get("schema"))
        success.append(f"`{status_code}` {schema}")
    return ", ".join(success) if success else "-"


def _parameters(operation: dict[str, Any]) -> str:
    params = operation.get("parameters") or []
    if not params:
        return "-"
    names = []
    for param in params:
        required = "*" if param.get("required") else ""
        location = param.get("in", "param")
        names.append(f"`{param.get('name', '?')}`{required} ({location})")
    return ", ".join(names)


def _requires_auth(operation: dict[str, Any]) -> str:
    security = operation.get("security")
    if security:
        return "yes"
    if security == []:
        return "no"
    return "no"


def _escape_table(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def render_openapi_reference(schema: dict[str, Any]) -> str:
    """Render a compact Markdown endpoint inventory from OpenAPI."""
    grouped: dict[str, list[tuple[str, str, dict[str, Any]]]] = defaultdict(list)
    for path, methods in sorted(schema.get("paths", {}).items()):
        for method in HTTP_METHODS:
            operation = methods.get(method)
            if not operation:
                continue
            tag = (operation.get("tags") or ["untagged"])[0]
            grouped[tag].append((method.upper(), path, operation))

    title = schema.get("info", {}).get("title", "Finance Report API")
    version = schema.get("info", {}).get("version", "unknown")
    lines = [
        "# Generated API Reference",
        "",
        "> Generated by `python tools/generate_api_reference.py`. Do not edit by hand.",
        "> The runtime OpenAPI schema is the API contract; use `/api/docs` or `/api/redoc` for full field-level details.",
        "",
        f"- API title: `{title}`",
        f"- API version: `{version}`",
        f"- Endpoint count: `{sum(len(items) for items in grouped.values())}`",
        f"- Schema count: `{len(schema.get('components', {}).get('schemas', {}))}`",
        "",
        "Paths below are backend OpenAPI paths. The production reverse proxy exposes them under `/api`.",
        "",
        "## Groups",
        "",
        "| Group | Endpoints |",
        "|---|---:|",
    ]
    for tag in sorted(grouped):
        lines.append(f"| `{tag}` | {len(grouped[tag])} |")

    lines.extend(["", "## Endpoints", ""])
    for tag in sorted(grouped):
        lines.extend(
            [
                f"### {tag}",
                "",
                "| Method | Path | Auth | Params | Request | Success responses | Summary |",
                "|---|---|---|---|---|---|---|",
            ]
        )
        for method, path, operation in grouped[tag]:
            summary = operation.get("summary") or operation.get("operationId") or ""
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{method}`",
                        f"`{path}`",
                        _requires_auth(operation),
                        _escape_table(_parameters(operation)),
                        _escape_table(_request_schema(operation)),
                        _escape_table(_response_schemas(operation)),
                        _escape_table(str(summary)),
                    ]
                )
                + " |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate() -> str:
    return render_openapi_reference(_load_openapi())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="Markdown output path.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated output differs from the checked-in file.",
    )
    args = parser.parse_args(argv)

    rendered = generate()
    output = args.output
    if args.check:
        try:
            current = output.read_text(encoding="utf-8")
        except OSError:
            print(
                f"ERROR: generated API reference is missing: {output}", file=sys.stderr
            )
            return 1
        if current != rendered:
            diff = difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile=str(output),
                tofile="generated",
                lineterm="",
            )
            print("ERROR: generated API reference is stale.", file=sys.stderr)
            print("\n".join(diff), file=sys.stderr)
            return 1
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
