from common.meta.base.package_contract import (
    ACRecord,
    ConceptRecord,
    PackageContract,
)

contract = PackageContract(
    name="ui_core",
    tier="CODE-ONLY",
    depends_on=[],
    events=[],
    interface=["app_config_router"],
    concepts=[
        ConceptRecord(
            key="api_client_pattern",
            owner="apps/frontend/frontend-patterns.md",
            description="Frontend MUST use lib/api.ts wrapper; never raw fetch().",
            family="frontend",
            cross_refs=[
                "AGENTS.md",
                "docs/agents/red-lines.md",
                "apps/frontend/src/lib/api.ts",
            ],
        ),
    ],
    invariants=[],
    roadmap=[
        ACRecord(
            id="AC-ui_core.16.23.1",
            statement="Stage 1 page split into `<PdfPreviewPane />`, `<TransactionTable />`, `<ReviewActionBar />`, `<BalanceIndicator />` components, each independently mountable",
            test="Manual UI test",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.23.2",
            statement="TransactionTable supports inline edit of `amount`, `description`, `date` with optimistic update + server confirm; failed write reverts row and shows error toast",
            test="Manual UI test",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.23.5",
            statement="Mobile navigation renders below 768 px (originally the `<MobileNav />` drawer; replaced by the `<BottomTabBar />` bottom tab bar per EPIC-022 AC22.21); the desktop sidebar is hidden on mobile",
            test="Manual UI test",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.11.32",
            statement="Vitest harness for Stage 1 split components — shared `renderReviewComponent()` helper in `apps/frontend/src/__tests__/helpers/`",
            test="Manual UI test",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.15.7.8",
            statement="Dashboard Processing card shows the signed current balance and a non-zero balance warning",
            test="`shows the current Processing Account balance when transfers are unresolved`",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.23.1",
            statement="Stage 1 page split into `<PdfPreviewPane />`, `<TransactionTable />`, `<ReviewActionBar />`, `<BalanceIndicator />` components, each independently mountable",
            test="Manual UI test",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.23.2",
            statement="TransactionTable supports inline edit of `amount`, `description`, `date` with optimistic update + server confirm; failed write reverts row and shows error toast",
            test="Manual UI test",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.23.5",
            statement="Mobile navigation renders below 768 px (originally the `<MobileNav />` drawer; replaced by the `<BottomTabBar />` bottom tab bar per EPIC-022 AC22.21); the desktop sidebar is hidden on mobile",
            test="Manual UI test",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.11.32",
            statement="Vitest harness for Stage 1 split components — shared `renderReviewComponent()` helper in `apps/frontend/src/__tests__/helpers/`",
            test="Manual UI test",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.15.7.8",
            statement="Dashboard Processing card shows the signed current balance and a non-zero balance warning",
            test="`shows the current Processing Account balance when transfers are unresolved`",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.1.10.4",
            statement="Frontend production dependency audits fail CI and CSP forbids `unsafe-eval` in shipped responses",
            test="`src/__tests__/api-urls.test.ts`, `.github/workflows/ci.yml`",
            priority="P1",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.1.2",
            statement="**Stage 1 UI shows PDF + parsed split view**",
            test="Manual UI test",
            priority="P0",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.19.11.1",
            statement="`/review/run/{runId}` uses run-scoped Stage 2 queue and batch-approval APIs so approving a run cannot approve pending matches from another workflow session or batch. Backend half (`test_AC19_11_1_stage2_run_queue_filters_by_run_id`) migrated to the `reconciliation` package roadmap as `AC-reconciliation.run-scoped-review.1` (migration closeout continuation, #1663 / #1711); the frontend half stays here.",
            test="`AC19.11.1 run review uses run-scoped queue and approval endpoints`",
            priority="P0",
            status="done",
        ),
        ACRecord(
            id="AC-ui_core.16.23.1",
            statement="Two-stage review UI capability (DROPPED)",
            test="TODO",
            priority="P0",
            status="open",
        ),
        ACRecord(
            id="AC-ui_core.19.11.1",
            statement="Event-driven upload to report UX (DROPPED)",
            test="TODO",
            priority="P0",
            status="open",
        ),
    ],
)
