"""Generate the frontend runtime operation table from the OpenAPI SSOT."""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from pathlib import Path


HTTP_METHODS = {"get", "put", "post", "delete", "patch", "options", "head", "trace"}


def render(spec_path: Path) -> str:
    payload = json.loads(spec_path.read_text(encoding="utf-8"))
    paths = payload.get("paths")
    if not isinstance(paths, dict):
        raise RuntimeError(f"{spec_path}: paths must be an object")
    records: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for path, path_item in sorted(paths.items()):
        if not isinstance(path_item, dict):
            raise RuntimeError(f"{spec_path}: path {path!r} must be an object")
        for method, operation in sorted(path_item.items()):
            if method not in HTTP_METHODS:
                continue
            if not isinstance(operation, dict) or not isinstance(
                operation.get("operationId"), str
            ):
                raise RuntimeError(
                    f"{spec_path}: {method.upper()} {path} has no operationId"
                )
            operation_id = operation["operationId"]
            if operation_id in seen:
                raise RuntimeError(
                    f"{spec_path}: duplicate operationId {operation_id!r}"
                )
            seen.add(operation_id)
            records.append((operation_id, method.upper(), f"/api{path}"))

    lines = [
        "// Generated by tools/generate_api_operations.py. Do not edit.",
        'import type { operations } from "./api-types";',
        "",
        "export interface ApiOperationDefinition {",
        "  readonly method: string;",
        "  readonly path: string;",
        "}",
        "",
        "export const API_OPERATIONS = {",
    ]
    for operation_id, method, path in sorted(records):
        lines.append(
            f"  {json.dumps(operation_id)}: {{ method: {json.dumps(method)}, "
            f"path: {json.dumps(path)} }},"
        )
    lines.extend(
        [
            "} as const satisfies Record<keyof operations, ApiOperationDefinition>;",
            "",
            "export type ApiOperationId = keyof typeof API_OPERATIONS;",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(args.spec), encoding="utf-8")
    return 0
