"""epic17: add portfolio models and extend positions"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '5e7857c97b74'
down_revision = '0013_add_consistency_checks'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types before using them
    op.execute("CREATE TYPE asset_type_enum AS ENUM ('stock', 'bond', 'etf', 'mutual_fund', 'property', 'cash', 'other')")
    op.execute("CREATE TYPE cost_basis_method_enum AS ENUM ('FIFO', 'LIFO', 'AvgCost')")

    op.create_table('market_data_override',
    sa.Column('asset_identifier', sa.String(length=100), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.Enum('manual', 'api', name='price_source_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_override_user_id'), 'market_data_override', ['user_id'], unique=False)
    op.create_table('dividend_income',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('dividend_type', sa.Enum('ordinary', 'qualified', name='dividend_type_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['managed_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_income_user_id'), 'dividend_income', ['user_id'], unique=False)
    op.drop_constraint(op.f('accounts_user_id_fkey'), 'accounts', type_='foreignkey')
    op.add_column('atomic_positions', sa.Column('asset_type', sa.Enum('stock', 'bond', 'etf', 'mutual_fund', 'property', 'cash', 'other', name='asset_type_enum'), nullable=True, comment='Asset classification'))
    op.add_column('atomic_positions', sa.Column('sector', sa.String(length=50), nullable=True, comment='Sector for allocation'))
    op.add_column('atomic_positions', sa.Column('geography', sa.String(length=50), nullable=True, comment='Country/region'))
    op.drop_index(op.f('idx_atomic_pos_date'), table_name='atomic_positions')
    op.drop_index(op.f('idx_atomic_pos_dedup'), table_name='atomic_positions')
    op.create_index(op.f('ix_atomic_positions_user_id'), 'atomic_positions', ['user_id'], unique=False)
    op.drop_constraint(op.f('atomic_positions_user_id_fkey'), 'atomic_positions', type_='foreignkey')
    op.drop_index(op.f('idx_atomic_txn_date'), table_name='atomic_transactions')
    op.drop_index(op.f('idx_atomic_txn_dedup'), table_name='atomic_transactions')
    op.create_index(op.f('ix_atomic_transactions_user_id'), 'atomic_transactions', ['user_id'], unique=False)
    op.drop_constraint(op.f('atomic_transactions_user_id_fkey'), 'atomic_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_bank_statement_transactions_status'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statement_transactions_txn_date'), table_name='bank_statement_transactions')
    op.drop_index(op.f('ix_bank_statements_status'), table_name='bank_statements')
    op.drop_constraint(op.f('bank_statements_user_id_fkey'), 'bank_statements', type_='foreignkey')
    op.drop_constraint(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_index(op.f('ix_classification_rules_user_id'), 'classification_rules', ['user_id'], unique=False)
    op.drop_constraint(op.f('classification_rules_user_id_fkey'), 'classification_rules', type_='foreignkey')
    op.alter_column('consistency_checks', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('consistency_checks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('consistency_checks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_consistency_checks_status'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_user_check_type_status'), table_name='consistency_checks')
    op.drop_constraint(op.f('journal_entries_user_id_fkey'), 'journal_entries', type_='foreignkey')
    op.alter_column('journal_lines', 'fx_rate',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.create_index(op.f('ix_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_journal_entry_id'), 'journal_lines', ['journal_entry_id'], unique=False)
    op.drop_constraint(op.f('journal_lines_journal_entry_id_fkey'), 'journal_lines', type_='foreignkey')
    op.create_foreign_key(None, 'journal_lines', 'journal_entries', ['journal_entry_id'], ['id'])
    op.add_column('managed_positions', sa.Column('cost_basis_method', sa.Enum('FIFO', 'LIFO', 'AvgCost', name='cost_basis_method_enum'), nullable=True, comment='Method for calculating realized P&L'))
    op.add_column('managed_positions', sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=True, comment='Unrealized gain/loss (market_value - cost_basis)'))
    op.add_column('managed_positions', sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=True, comment='Realized gain/loss from disposals'))
    op.create_index(op.f('ix_managed_positions_user_id'), 'managed_positions', ['user_id'], unique=False)
    op.drop_constraint(op.f('managed_positions_user_id_fkey'), 'managed_positions', type_='foreignkey')
    op.drop_index(op.f('idx_reconciliation_matches_atomic_txn'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_status'), table_name='reconciliation_matches')
    op.create_index(op.f('ix_report_snapshots_user_id'), 'report_snapshots', ['user_id'], unique=False)
    op.drop_constraint(op.f('report_snapshots_user_id_fkey'), 'report_snapshots', type_='foreignkey')
    op.create_index(op.f('ix_uploaded_documents_user_id'), 'uploaded_documents', ['user_id'], unique=False)
    op.drop_constraint(op.f('uploaded_documents_user_id_fkey'), 'uploaded_documents', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('uploaded_documents_user_id_fkey'), 'uploaded_documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_uploaded_documents_user_id'), table_name='uploaded_documents')
    op.create_foreign_key(op.f('report_snapshots_user_id_fkey'), 'report_snapshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_report_snapshots_user_id'), table_name='report_snapshots')
    op.create_index(op.f('ix_reconciliation_matches_status'), 'reconciliation_matches', ['status'], unique=False)
    op.create_index(op.f('idx_reconciliation_matches_atomic_txn'), 'reconciliation_matches', ['atomic_txn_id'], unique=False)
    op.create_foreign_key(op.f('managed_positions_user_id_fkey'), 'managed_positions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_managed_positions_user_id'), table_name='managed_positions')
    op.drop_column('managed_positions', 'realized_pnl')
    op.drop_column('managed_positions', 'unrealized_pnl')
    op.drop_column('managed_positions', 'cost_basis_method')
    op.drop_constraint(None, 'journal_lines', type_='foreignkey')
    op.create_foreign_key(op.f('journal_lines_journal_entry_id_fkey'), 'journal_lines', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_journal_lines_journal_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_id'), table_name='journal_lines')
    op.alter_column('journal_lines', 'fx_rate',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=sa.NUMERIC(precision=12, scale=6),
               existing_nullable=True)
    op.create_foreign_key(op.f('journal_entries_user_id_fkey'), 'journal_entries', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_consistency_checks_user_check_type_status'), 'consistency_checks', ['user_id', 'check_type', 'status'], unique=False)
    op.create_index(op.f('ix_consistency_checks_status'), 'consistency_checks', ['status'], unique=False)
    op.alter_column('consistency_checks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('consistency_checks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('consistency_checks', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.create_foreign_key(op.f('classification_rules_user_id_fkey'), 'classification_rules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_classification_rules_user_id'), table_name='classification_rules')
    op.create_foreign_key(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('bank_statements_user_id_fkey'), 'bank_statements', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_bank_statements_status'), 'bank_statements', ['status'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_txn_date'), 'bank_statement_transactions', ['txn_date'], unique=False)
    op.create_index(op.f('ix_bank_statement_transactions_status'), 'bank_statement_transactions', ['status'], unique=False)
    op.create_foreign_key(op.f('atomic_transactions_user_id_fkey'), 'atomic_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_atomic_transactions_user_id'), table_name='atomic_transactions')
    op.create_index(op.f('idx_atomic_txn_dedup'), 'atomic_transactions', ['user_id', 'dedup_hash'], unique=False)
    op.create_index(op.f('idx_atomic_txn_date'), 'atomic_transactions', ['user_id', 'txn_date'], unique=False)
    op.create_foreign_key(op.f('atomic_positions_user_id_fkey'), 'atomic_positions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_atomic_positions_user_id'), table_name='atomic_positions')
    op.create_index(op.f('idx_atomic_pos_dedup'), 'atomic_positions', ['user_id', 'dedup_hash'], unique=False)
    op.create_index(op.f('idx_atomic_pos_date'), 'atomic_positions', ['user_id', 'snapshot_date'], unique=False)
    op.drop_column('atomic_positions', 'geography')
    op.drop_column('atomic_positions', 'sector')
    op.drop_column('atomic_positions', 'asset_type')
    op.create_foreign_key(op.f('accounts_user_id_fkey'), 'accounts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_dividend_income_user_id'), table_name='dividend_income')
    op.drop_table('dividend_income')
    op.drop_index(op.f('ix_market_data_override_user_id'), table_name='market_data_override')
    op.drop_table('market_data_override')
    # ### end Alembic commands ###
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS cost_basis_method_enum")
    op.execute("DROP TYPE IF EXISTS asset_type_enum")
