"""Restore cascading FKs"""

from alembic import op
import sqlalchemy as sa



revision = 'bc9a8105e644'
down_revision = '0014_add_correction_logs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'atomic_positions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'atomic_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bank_statements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'classification_rules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'consistency_checks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('correction_logs', 'original_category',
               existing_type=sa.VARCHAR(length=100),
               comment='AI-suggested category before correction',
               existing_nullable=True)
    op.alter_column('correction_logs', 'corrected_category',
               existing_type=sa.VARCHAR(length=100),
               comment='User-corrected category',
               existing_nullable=False)
    op.alter_column('correction_logs', 'transaction_description',
               existing_type=sa.TEXT(),
               comment='Cached transaction description for few-shot prompt building',
               existing_nullable=True)
    op.create_foreign_key(None, 'dividend_income', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'journal_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('journal_lines_journal_entry_id_fkey'), 'journal_lines', type_='foreignkey')
    op.create_foreign_key(None, 'journal_lines', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'managed_positions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'market_data_override', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'report_snapshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'uploaded_documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_documents', type_='foreignkey')
    op.drop_constraint(None, 'report_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'market_data_override', type_='foreignkey')
    op.drop_constraint(None, 'managed_positions', type_='foreignkey')
    op.drop_constraint(None, 'journal_lines', type_='foreignkey')
    op.create_foreign_key(op.f('journal_lines_journal_entry_id_fkey'), 'journal_lines', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_constraint(None, 'dividend_income', type_='foreignkey')
    op.alter_column('correction_logs', 'transaction_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Cached transaction description for few-shot prompt building',
               existing_nullable=True)
    op.alter_column('correction_logs', 'corrected_category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='User-corrected category',
               existing_nullable=False)
    op.alter_column('correction_logs', 'original_category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='AI-suggested category before correction',
               existing_nullable=True)
    op.drop_constraint(None, 'consistency_checks', type_='foreignkey')
    op.drop_constraint(None, 'classification_rules', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'bank_statements', type_='foreignkey')
    op.drop_constraint(None, 'atomic_transactions', type_='foreignkey')
    op.drop_constraint(None, 'atomic_positions', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    # ### end Alembic commands ###
