"""Pydantic schemas package.

Exports are lazy (PEP 562): importing any ``src.schemas.<module>`` leaf must not
eagerly initialize every schema module — several import domain package roots,
and an eager hub turns any leaf import into a package-root import chain
(circular-import class exposed by the #1675 ORM decentralization).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

_LAZY = {
    "AccountCoverageCadence": ("src.schemas.account", "AccountCoverageCadence"),
    "AccountCoverageIssue": ("src.schemas.account", "AccountCoverageIssue"),
    "AccountCoverageIssueType": ("src.schemas.account", "AccountCoverageIssueType"),
    "AccountCoverageListResponse": ("src.schemas.account", "AccountCoverageListResponse"),
    "AccountCoverageResponse": ("src.schemas.account", "AccountCoverageResponse"),
    "AccountCreate": ("src.schemas.account", "AccountCreate"),
    "AccountLineageLine": ("src.schemas.reporting", "AccountLineageLine"),
    "AccountLineageResponse": ("src.schemas.reporting", "AccountLineageResponse"),
    "AccountListResponse": ("src.schemas.account", "AccountListResponse"),
    "AccountResponse": ("src.schemas.account", "AccountResponse"),
    "AccountTrendResponse": ("src.schemas.reporting", "AccountTrendResponse"),
    "AccountUpdate": ("src.schemas.account", "AccountUpdate"),
    "AnnualizedIncomeScheduleHolding": ("src.schemas.reporting", "AnnualizedIncomeScheduleHolding"),
    "AnnualizedIncomeScheduleIncome": ("src.schemas.reporting", "AnnualizedIncomeScheduleIncome"),
    "AnnualizedIncomeScheduleNetWorthTreatment": ("src.schemas.reporting", "AnnualizedIncomeScheduleNetWorthTreatment"),
    "AnnualizedIncomeScheduleResponse": ("src.schemas.reporting", "AnnualizedIncomeScheduleResponse"),
    "AnomalyResponse": ("src.schemas.reconciliation", "AnomalyResponse"),
    "AtomicTransactionResponse": ("src.schemas.extraction", "AtomicTransactionResponse"),
    "BalanceSheetResponse": ("src.schemas.reporting", "BalanceSheetResponse"),
    "BankStatementListResponse": ("src.schemas.extraction", "BankStatementListResponse"),
    "BankStatementResponse": ("src.schemas.extraction", "BankStatementResponse"),
    "BankStatementStatusEnum": ("src.schemas.extraction", "BankStatementStatusEnum"),
    "BankStatementTransactionListResponse": ("src.schemas.extraction", "BankStatementTransactionListResponse"),
    "BankStatementUploadRequest": ("src.schemas.extraction", "BankStatementUploadRequest"),
    "BankTransactionSummary": ("src.schemas.reconciliation", "BankTransactionSummary"),
    "BatchAcceptRequest": ("src.schemas.reconciliation", "BatchAcceptRequest"),
    "BatchApproveRequest": ("src.schemas.review", "BatchApproveRequest"),
    "BatchRejectRequest": ("src.schemas.review", "BatchRejectRequest"),
    "BreakdownPeriod": ("src.schemas.reporting", "BreakdownPeriod"),
    "BreakdownType": ("src.schemas.reporting", "BreakdownType"),
    "COMMON_ERROR_RESPONSES": ("src.schemas.errors", "COMMON_ERROR_RESPONSES"),
    "CashFlowItem": ("src.schemas.reporting", "CashFlowItem"),
    "CashFlowResponse": ("src.schemas.reporting", "CashFlowResponse"),
    "CashFlowSummary": ("src.schemas.reporting", "CashFlowSummary"),
    "CategoryBreakdownResponse": ("src.schemas.reporting", "CategoryBreakdownResponse"),
    "ChatHistoryResponse": ("src.schemas.chat", "ChatHistoryResponse"),
    "ChatMessageResponse": ("src.schemas.chat", "ChatMessageResponse"),
    "ChatRequest": ("src.schemas.chat", "ChatRequest"),
    "ChatSessionResponse": ("src.schemas.chat", "ChatSessionResponse"),
    "ChatSuggestionsResponse": ("src.schemas.chat", "ChatSuggestionsResponse"),
    "ConsistencyCheckListResponse": ("src.schemas.review", "ConsistencyCheckListResponse"),
    "ConsistencyCheckResponse": ("src.schemas.review", "ConsistencyCheckResponse"),
    "ErrorCode": ("src.schemas.errors", "ErrorCode"),
    "ErrorResponse": ("src.schemas.errors", "ErrorResponse"),
    "FrameworkPolicyDecision": ("src.schemas.reporting", "FrameworkPolicyDecision"),
    "FrameworkPolicyEvidenceAnchor": ("src.schemas.reporting", "FrameworkPolicyEvidenceAnchor"),
    "FrameworkPolicyFact": ("src.schemas.reporting", "FrameworkPolicyFact"),
    "FrameworkPolicyGap": ("src.schemas.reporting", "FrameworkPolicyGap"),
    "FrameworkPolicyMatrix": ("src.schemas.reporting", "FrameworkPolicyMatrix"),
    "FrameworkPolicyMatrixRule": ("src.schemas.reporting", "FrameworkPolicyMatrixRule"),
    "FrameworkPolicyResult": ("src.schemas.reporting", "FrameworkPolicyResult"),
    "IncomeStatementResponse": ("src.schemas.reporting", "IncomeStatementResponse"),
    "JournalEntryCreate": ("src.schemas.journal", "JournalEntryCreate"),
    "JournalEntryListResponse": ("src.schemas.journal", "JournalEntryListResponse"),
    "JournalEntryResponse": ("src.schemas.journal", "JournalEntryResponse"),
    "JournalEntrySummary": ("src.schemas.reconciliation", "JournalEntrySummary"),
    "JournalLineCreate": ("src.schemas.journal", "JournalLineCreate"),
    "JournalLineResponse": ("src.schemas.journal", "JournalLineResponse"),
    "ManagedPositionListResponse": ("src.schemas.assets", "ManagedPositionListResponse"),
    "ManagedPositionResponse": ("src.schemas.assets", "ManagedPositionResponse"),
    "NetWorthAllocationResponse": ("src.schemas.reporting", "NetWorthAllocationResponse"),
    "NetWorthAllocationRow": ("src.schemas.reporting", "NetWorthAllocationRow"),
    "NetWorthAllocationSourceLine": ("src.schemas.reporting", "NetWorthAllocationSourceLine"),
    "NetWorthGranularity": ("src.schemas.reporting", "NetWorthGranularity"),
    "NetWorthTimeSeriesResponse": ("src.schemas.reporting", "NetWorthTimeSeriesResponse"),
    "ParsedStatementPreview": ("src.schemas.extraction", "ParsedStatementPreview"),
    "PersonalReportPackageCompletenessWarning": ("src.schemas.reporting", "PersonalReportPackageCompletenessWarning"),
    "PersonalReportPackageContractResponse": ("src.schemas.reporting", "PersonalReportPackageContractResponse"),
    "PersonalReportPackageDocument": ("src.schemas.reporting", "PersonalReportPackageDocument"),
    "PersonalReportPackageDocumentLifecycle": ("src.schemas.reporting", "PersonalReportPackageDocumentLifecycle"),
    "PersonalReportPackageDocumentSummary": ("src.schemas.reporting", "PersonalReportPackageDocumentSummary"),
    "PersonalReportPackageExportContract": ("src.schemas.reporting", "PersonalReportPackageExportContract"),
    "PersonalReportPackageGenerateRequest": ("src.schemas.reporting", "PersonalReportPackageGenerateRequest"),
    "PersonalReportPackageInputCoverage": ("src.schemas.reporting", "PersonalReportPackageInputCoverage"),
    "PersonalReportPackageNote": ("src.schemas.reporting", "PersonalReportPackageNote"),
    "PersonalReportPackageNotesResponse": ("src.schemas.reporting", "PersonalReportPackageNotesResponse"),
    "PersonalReportPackageReadinessBlocker": ("src.schemas.reporting", "PersonalReportPackageReadinessBlocker"),
    "PersonalReportPackageReadinessResponse": ("src.schemas.reporting", "PersonalReportPackageReadinessResponse"),
    "PersonalReportPackageReadinessState": ("src.schemas.reporting", "PersonalReportPackageReadinessState"),
    "PersonalReportPackageSectionContract": ("src.schemas.reporting", "PersonalReportPackageSectionContract"),
    "PersonalReportPackageSnapshotResponse": ("src.schemas.reporting", "PersonalReportPackageSnapshotResponse"),
    "PersonalReportPackageSnapshotStatus": ("src.schemas.reporting", "PersonalReportPackageSnapshotStatus"),
    "PersonalReportPackageSnapshotSummary": ("src.schemas.reporting", "PersonalReportPackageSnapshotSummary"),
    "PersonalReportPackageSections": ("src.schemas.reporting", "PersonalReportPackageSections"),
    "PersonalReportPackageTraceManifestEntry": ("src.schemas.reporting", "PersonalReportPackageTraceManifestEntry"),
    "PersonalReportPackageTraceabilityAnchor": ("src.schemas.reporting", "PersonalReportPackageTraceabilityAnchor"),
    "PersonalReportPackageTraceabilityLine": ("src.schemas.reporting", "PersonalReportPackageTraceabilityLine"),
    "PersonalReportPackageTraceabilityResponse": ("src.schemas.reporting", "PersonalReportPackageTraceabilityResponse"),
    "PersonalReportingFrameworkId": ("src.schemas.reporting", "PersonalReportingFrameworkId"),
    "PingStateResponse": ("src.schemas.ping", "PingStateResponse"),
    "PolicyDimension": ("src.schemas.reporting", "PolicyDimension"),
    "PolicyFactDomain": ("src.schemas.reporting", "PolicyFactDomain"),
    "PolicyProvenance": ("src.schemas.reporting", "PolicyProvenance"),
    "PolicyReviewState": ("src.schemas.reporting", "PolicyReviewState"),
    "ProcessingPendingItem": ("src.schemas.account", "ProcessingPendingItem"),
    "ProcessingPendingListResponse": ("src.schemas.account", "ProcessingPendingListResponse"),
    "ProcessingSummaryResponse": ("src.schemas.account", "ProcessingSummaryResponse"),
    "ReconcilePositionsResponse": ("src.schemas.assets", "ReconcilePositionsResponse"),
    "ReconciliationMatchListResponse": ("src.schemas.reconciliation", "ReconciliationMatchListResponse"),
    "ReconciliationMatchResponse": ("src.schemas.reconciliation", "ReconciliationMatchResponse"),
    "ReconciliationRunRequest": ("src.schemas.reconciliation", "ReconciliationRunRequest"),
    "ReconciliationRunResponse": ("src.schemas.reconciliation", "ReconciliationRunResponse"),
    "ReconciliationStatsResponse": ("src.schemas.reconciliation", "ReconciliationStatsResponse"),
    "ReconciliationStatusEnum": ("src.schemas.reconciliation", "ReconciliationStatusEnum"),
    "ReportSnapshotSummary": ("src.schemas.reporting", "ReportSnapshotSummary"),
    "ResolveCheckRequest": ("src.schemas.review", "ResolveCheckRequest"),
    "RetryParsingRequest": ("src.schemas.extraction", "RetryParsingRequest"),
    "Stage2ReviewQueueResponse": ("src.schemas.review", "Stage2ReviewQueueResponse"),
    "StatementDecisionRequest": ("src.schemas.extraction", "StatementDecisionRequest"),
    "TrendPeriod": ("src.schemas.reporting", "TrendPeriod"),
    "UnmatchedTransactionsResponse": ("src.schemas.reconciliation", "UnmatchedTransactionsResponse"),
    "UserAiSettingsResponse": ("src.schemas.user", "UserAiSettingsResponse"),
    "UserAiSettingsUpdate": ("src.schemas.user", "UserAiSettingsUpdate"),
    "UserCreate": ("src.schemas.user", "UserCreate"),
    "UserListResponse": ("src.schemas.user", "UserListResponse"),
    "UserResponse": ("src.schemas.user", "UserResponse"),
    "UserUpdate": ("src.schemas.user", "UserUpdate"),
    "VoidJournalEntryRequest": ("src.schemas.journal", "VoidJournalEntryRequest"),
    "WorkflowEventCountsResponse": ("src.schemas.workflow", "WorkflowEventCountsResponse"),
    "WorkflowEventCreate": ("src.schemas.workflow", "WorkflowEventCreate"),
    "WorkflowEventListResponse": ("src.schemas.workflow", "WorkflowEventListResponse"),
    "WorkflowEventResponse": ("src.schemas.workflow", "WorkflowEventResponse"),
    "WorkflowEventStatusUpdate": ("src.schemas.workflow", "WorkflowEventStatusUpdate"),
    "WorkflowNextActionResponse": ("src.schemas.workflow", "WorkflowNextActionResponse"),
    "WorkflowNextActionType": ("src.schemas.workflow", "WorkflowNextActionType"),
    "WorkflowPrimaryState": ("src.schemas.workflow", "WorkflowPrimaryState"),
    "WorkflowReportImpact": ("src.schemas.workflow", "WorkflowReportImpact"),
    "WorkflowReportReadinessResponse": ("src.schemas.workflow", "WorkflowReportReadinessResponse"),
    "WorkflowReportReadinessState": ("src.schemas.workflow", "WorkflowReportReadinessState"),
    "WorkflowStatusResponse": ("src.schemas.workflow", "WorkflowStatusResponse"),
    "compose_statement_response": ("src.schemas.extraction", "compose_statement_response"),
    "error_code_for_status": ("src.schemas.errors", "error_code_for_status"),
}

__all__ = [
    "AccountCoverageCadence",
    "AccountCoverageIssue",
    "AccountCoverageIssueType",
    "AccountCoverageListResponse",
    "AccountCoverageResponse",
    "AccountCreate",
    "AccountLineageLine",
    "AccountLineageResponse",
    "AccountListResponse",
    "AccountResponse",
    "AccountTrendResponse",
    "AccountUpdate",
    "AnnualizedIncomeScheduleHolding",
    "AnnualizedIncomeScheduleIncome",
    "AnnualizedIncomeScheduleNetWorthTreatment",
    "AnnualizedIncomeScheduleResponse",
    "AnomalyResponse",
    "AtomicTransactionResponse",
    "BalanceSheetResponse",
    "BankStatementListResponse",
    "BankStatementResponse",
    "BankStatementStatusEnum",
    "BankStatementTransactionListResponse",
    "BankStatementUploadRequest",
    "BankTransactionSummary",
    "BatchAcceptRequest",
    "BatchApproveRequest",
    "BatchRejectRequest",
    "BreakdownPeriod",
    "BreakdownType",
    "COMMON_ERROR_RESPONSES",
    "CashFlowItem",
    "CashFlowResponse",
    "CashFlowSummary",
    "CategoryBreakdownResponse",
    "ChatHistoryResponse",
    "ChatMessageResponse",
    "ChatRequest",
    "ChatSessionResponse",
    "ChatSuggestionsResponse",
    "ConsistencyCheckListResponse",
    "ConsistencyCheckResponse",
    "ErrorCode",
    "ErrorResponse",
    "FrameworkPolicyDecision",
    "FrameworkPolicyEvidenceAnchor",
    "FrameworkPolicyFact",
    "FrameworkPolicyGap",
    "FrameworkPolicyMatrix",
    "FrameworkPolicyMatrixRule",
    "FrameworkPolicyResult",
    "IncomeStatementResponse",
    "JournalEntryCreate",
    "JournalEntryListResponse",
    "JournalEntryResponse",
    "JournalEntrySummary",
    "JournalLineCreate",
    "JournalLineResponse",
    "ManagedPositionListResponse",
    "ManagedPositionResponse",
    "NetWorthAllocationResponse",
    "NetWorthAllocationRow",
    "NetWorthAllocationSourceLine",
    "NetWorthGranularity",
    "NetWorthTimeSeriesResponse",
    "ParsedStatementPreview",
    "PersonalReportPackageCompletenessWarning",
    "PersonalReportPackageContractResponse",
    "PersonalReportPackageDocument",
    "PersonalReportPackageDocumentLifecycle",
    "PersonalReportPackageDocumentSummary",
    "PersonalReportPackageExportContract",
    "PersonalReportPackageGenerateRequest",
    "PersonalReportPackageInputCoverage",
    "PersonalReportPackageNote",
    "PersonalReportPackageNotesResponse",
    "PersonalReportPackageReadinessBlocker",
    "PersonalReportPackageReadinessResponse",
    "PersonalReportPackageReadinessState",
    "PersonalReportPackageSectionContract",
    "PersonalReportPackageSnapshotResponse",
    "PersonalReportPackageSnapshotStatus",
    "PersonalReportPackageSnapshotSummary",
    "PersonalReportPackageSections",
    "PersonalReportPackageTraceManifestEntry",
    "PersonalReportPackageTraceabilityAnchor",
    "PersonalReportPackageTraceabilityLine",
    "PersonalReportPackageTraceabilityResponse",
    "PersonalReportingFrameworkId",
    "PingStateResponse",
    "PolicyDimension",
    "PolicyFactDomain",
    "PolicyProvenance",
    "PolicyReviewState",
    "ProcessingPendingItem",
    "ProcessingPendingListResponse",
    "ProcessingSummaryResponse",
    "ReconcilePositionsResponse",
    "ReconciliationMatchListResponse",
    "ReconciliationMatchResponse",
    "ReconciliationRunRequest",
    "ReconciliationRunResponse",
    "ReconciliationStatsResponse",
    "ReconciliationStatusEnum",
    "ReportSnapshotSummary",
    "ResolveCheckRequest",
    "RetryParsingRequest",
    "Stage2ReviewQueueResponse",
    "StatementDecisionRequest",
    "TrendPeriod",
    "UnmatchedTransactionsResponse",
    "UserAiSettingsResponse",
    "UserAiSettingsUpdate",
    "UserCreate",
    "UserListResponse",
    "UserResponse",
    "UserUpdate",
    "VoidJournalEntryRequest",
    "WorkflowEventCountsResponse",
    "WorkflowEventCreate",
    "WorkflowEventListResponse",
    "WorkflowEventResponse",
    "WorkflowEventStatusUpdate",
    "WorkflowNextActionResponse",
    "WorkflowNextActionType",
    "WorkflowPrimaryState",
    "WorkflowReportImpact",
    "WorkflowReportReadinessResponse",
    "WorkflowReportReadinessState",
    "WorkflowStatusResponse",
    "compose_statement_response",
    "error_code_for_status",
]


def __getattr__(name: str) -> object:
    """Lazily import and return a published schema symbol (PEP 562)."""
    entry = _LAZY.get(name)
    if entry is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    import importlib

    module_path, attr = entry
    value = getattr(importlib.import_module(module_path), attr)
    globals()[name] = value
    return value


if TYPE_CHECKING:  # pragma: no cover - static view of the lazy exports
    from src.schemas.account import (
        AccountCoverageCadence,
        AccountCoverageIssue,
        AccountCoverageIssueType,
        AccountCoverageListResponse,
        AccountCoverageResponse,
        AccountCreate,
        AccountListResponse,
        AccountResponse,
        AccountUpdate,
        ProcessingPendingItem,
        ProcessingPendingListResponse,
        ProcessingSummaryResponse,
    )
    from src.schemas.assets import (
        ManagedPositionListResponse,
        ManagedPositionResponse,
        ReconcilePositionsResponse,
    )
    from src.schemas.chat import (
        ChatHistoryResponse,
        ChatMessageResponse,
        ChatRequest,
        ChatSessionResponse,
        ChatSuggestionsResponse,
    )
    from src.schemas.errors import (
        COMMON_ERROR_RESPONSES,
        ErrorCode,
        ErrorResponse,
        error_code_for_status,
    )
    from src.schemas.extraction import (
        AtomicTransactionResponse,
        BankStatementListResponse,
        BankStatementResponse,
        BankStatementStatusEnum,
        BankStatementTransactionListResponse,
        BankStatementUploadRequest,
        ParsedStatementPreview,
        RetryParsingRequest,
        StatementDecisionRequest,
        compose_statement_response,
    )
    from src.schemas.journal import (
        JournalEntryCreate,
        JournalEntryListResponse,
        JournalEntryResponse,
        JournalLineCreate,
        JournalLineResponse,
        VoidJournalEntryRequest,
    )
    from src.schemas.ping import (
        PingStateResponse,
    )
    from src.schemas.reconciliation import (
        AnomalyResponse,
        BankTransactionSummary,
        BatchAcceptRequest,
        JournalEntrySummary,
        ReconciliationMatchListResponse,
        ReconciliationMatchResponse,
        ReconciliationRunRequest,
        ReconciliationRunResponse,
        ReconciliationStatsResponse,
        ReconciliationStatusEnum,
        UnmatchedTransactionsResponse,
    )
    from src.schemas.reporting import (
        AccountLineageLine,
        AccountLineageResponse,
        AccountTrendResponse,
        AnnualizedIncomeScheduleHolding,
        AnnualizedIncomeScheduleIncome,
        AnnualizedIncomeScheduleNetWorthTreatment,
        AnnualizedIncomeScheduleResponse,
        BalanceSheetResponse,
        BreakdownPeriod,
        BreakdownType,
        CashFlowItem,
        CashFlowResponse,
        CashFlowSummary,
        CategoryBreakdownResponse,
        FrameworkPolicyDecision,
        FrameworkPolicyEvidenceAnchor,
        FrameworkPolicyFact,
        FrameworkPolicyGap,
        FrameworkPolicyMatrix,
        FrameworkPolicyMatrixRule,
        FrameworkPolicyResult,
        IncomeStatementResponse,
        NetWorthAllocationResponse,
        NetWorthAllocationRow,
        NetWorthAllocationSourceLine,
        NetWorthGranularity,
        NetWorthTimeSeriesResponse,
        PersonalReportingFrameworkId,
        PersonalReportPackageCompletenessWarning,
        PersonalReportPackageContractResponse,
        PersonalReportPackageDocument,
        PersonalReportPackageDocumentLifecycle,
        PersonalReportPackageDocumentSummary,
        PersonalReportPackageExportContract,
        PersonalReportPackageGenerateRequest,
        PersonalReportPackageInputCoverage,
        PersonalReportPackageNote,
        PersonalReportPackageNotesResponse,
        PersonalReportPackageReadinessBlocker,
        PersonalReportPackageReadinessResponse,
        PersonalReportPackageReadinessState,
        PersonalReportPackageSectionContract,
        PersonalReportPackageSections,
        PersonalReportPackageSnapshotResponse,
        PersonalReportPackageSnapshotStatus,
        PersonalReportPackageSnapshotSummary,
        PersonalReportPackageTraceabilityAnchor,
        PersonalReportPackageTraceabilityLine,
        PersonalReportPackageTraceabilityResponse,
        PersonalReportPackageTraceManifestEntry,
        PolicyDimension,
        PolicyFactDomain,
        PolicyProvenance,
        PolicyReviewState,
        ReportSnapshotSummary,
        TrendPeriod,
    )
    from src.schemas.review import (
        BatchApproveRequest,
        BatchRejectRequest,
        ConsistencyCheckListResponse,
        ConsistencyCheckResponse,
        ResolveCheckRequest,
        Stage2ReviewQueueResponse,
    )
    from src.schemas.user import (
        UserAiSettingsResponse,
        UserAiSettingsUpdate,
        UserCreate,
        UserListResponse,
        UserResponse,
        UserUpdate,
    )
    from src.schemas.workflow import (
        WorkflowEventCountsResponse,
        WorkflowEventCreate,
        WorkflowEventListResponse,
        WorkflowEventResponse,
        WorkflowEventStatusUpdate,
        WorkflowNextActionResponse,
        WorkflowNextActionType,
        WorkflowPrimaryState,
        WorkflowReportImpact,
        WorkflowReportReadinessResponse,
        WorkflowReportReadinessState,
        WorkflowStatusResponse,
    )
