"""Co-located critical-proof declarations.

``docs/ssot/critical-proof-matrix.yaml`` used to be a hand-maintained CENTRAL
index: every behavioural-anchoring PR appended a ``proofs[]`` entry, so PRs that
anchored *different* ACs collided textually on the same file (false sharing) and
were forced through a linear merge train.

This module moves the proof declaration to the source of truth — the test
itself — exactly like ``docs/ac_registry.yaml`` is generated from EPIC docs. A
PR anchoring a new AC now edits only its OWN test file (adds an ``@ac_proof``
decorator); the central YAML is a GENERATED artifact, regenerated by
``tools/generate_critical_proof_matrix.py`` and verified with ``--check``.

The decorator is a pure runtime **no-op**: it returns the test function
unchanged and attaches the metadata as ``__ac_proof__`` for introspection. The
generator never imports the test tree — it scans ``@ac_proof(...)`` calls
statically with ``ast`` (consistent with ``check_critical_proof_matrix.py``), so
the literal arguments are the single source of truth and must be plain literals.

stdlib-only by design: importable from any test suite (backend, e2e, frontend
helpers) without pulling app or framework dependencies.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import TypeVar

F = TypeVar("F", bound=Callable[..., object])

# The marker attribute the decorator attaches to the wrapped function. The
# generator does not read this (it scans statically); it exists for runtime
# introspection and tests.
PROOF_ATTR = "__ac_proof__"


@dataclass(frozen=True)
class AcProof:
    """One co-located critical-proof declaration.

    Mirrors a ``proofs[]`` entry in ``critical-proof-matrix.yaml``. ``file`` and
    ``test`` are derived by the generator from the decorated function's location
    and name, so they are intentionally absent here.
    """

    proof_id: str
    ac_ids: tuple[str, ...]
    scope: str = "behavioral"
    ci_tier: str = "post_merge_environment"
    trust_mode: str = ""
    source_classes: tuple[str, ...] = ()
    mirror_proof_id: str = ""
    issue: str = ""
    required_markers: tuple[str, ...] = ()
    outcomes: tuple[str, ...] = field(default_factory=tuple)


def ac_proof(
    proof_id: str,
    *,
    ac_ids: list[str] | tuple[str, ...],
    scope: str = "behavioral",
    ci_tier: str = "post_merge_environment",
    trust_mode: str = "",
    source_classes: list[str] | tuple[str, ...] = (),
    mirror_proof_id: str = "",
    issue: str = "",
    required_markers: list[str] | tuple[str, ...] = (),
    outcomes: list[str] | tuple[str, ...] = (),
) -> Callable[[F], F]:
    """Declare that the decorated test is a critical-proof path.

    Runtime no-op: the decorated function is returned unchanged, with the
    declaration attached as ``func.__ac_proof__`` for introspection. The proof
    matrix YAML is regenerated from these declarations by
    ``tools/generate_critical_proof_matrix.py``.

    Arguments mirror a ``proofs[]`` entry; ``file`` and ``test`` are derived by
    the generator. Keep every argument a plain literal — the generator reads
    them statically and rejects non-literal values.
    """

    proof = AcProof(
        proof_id=proof_id,
        ac_ids=tuple(ac_ids),
        scope=scope,
        ci_tier=ci_tier,
        trust_mode=trust_mode,
        source_classes=tuple(source_classes),
        mirror_proof_id=mirror_proof_id,
        issue=issue,
        required_markers=tuple(required_markers),
        outcomes=tuple(outcomes),
    )

    def decorate(func: F) -> F:
        setattr(func, PROOF_ATTR, proof)
        return func

    return decorate
