#!/usr/bin/env python3
"""Generate the backend env block of ``.env.example`` and an env-reference doc.

Infra-014 C3: the backend portion of ``.env.example`` and
``common/runtime/env-reference.generated.md`` are generated directly from the
``Settings(BaseSettings)`` pydantic metadata in ``apps/backend/src/config.py``
(``description=`` and ``json_schema_extra={...}``) so they can never drift from
the code.

#1828 G-injection-drift-gate: the same single source of truth also emits a
machine-readable required-env manifest
(``common/runtime/required-env.generated.json``) that infra2 consumes to check
its ``secrets.ctmpl`` injection template in CI (the #876 artifact boundary).
``tests/tooling/test_required_env_manifest.py`` locks manifest ↔ config ↔
``.env.example`` in both directions.

Only the backend block of ``.env.example`` is managed (delimited by sentinel
markers). The frontend block below the markers (``NEXT_PUBLIC_*``,
``OPENPANEL_*``) is preserved verbatim because those keys are not defined in
``config.py``.

Usage:
    python tools/generate_env_reference.py            # write files
    python tools/generate_env_reference.py --check    # exit 1 if files drift
"""

from __future__ import annotations

import argparse
import difflib
import sys
from collections.abc import Sequence
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "apps" / "backend"

# Repo root on sys.path[0] when run directly (tool-wrapper contract AC8.13.56).
# Backend imports (pydantic, src.config) are loaded lazily in ``_settings_model``
# so importing this module never perturbs sys.path[0] or requires backend deps.
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))


def _settings_module():
    """Load config.py by explicit file path (see ``_settings_model``)."""
    import importlib.util

    config_path = BACKEND_DIR / "src" / "config.py"
    spec = importlib.util.spec_from_file_location("_env_reference_config", config_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _settings_model():
    """Load the backend ``Settings`` class from config.py by explicit file path.

    Loading by path (rather than ``from src.config import Settings``) avoids any
    ambiguity from a cached/namespace ``src`` package contributed by other tests,
    and keeps sys.path untouched (tool-wrapper contract AC8.13.56). config.py only
    imports pydantic, so it loads standalone given the backend env.
    """
    return _settings_module().Settings


ENV_EXAMPLE_PATH = ROOT_DIR / ".env.example"
ENV_REFERENCE_DOC_PATH = ROOT_DIR / "common" / "runtime" / "env-reference.generated.md"
MANIFEST_SOURCE = "apps/backend/src/config.py::Settings"
REQUIRED_ENV_MANIFEST_PATH = (
    ROOT_DIR / "common" / "runtime" / "required-env.generated.json"
)

BEGIN_MARKER = "# >>> generated by tools/generate_env_reference.py — do not edit (backend, from config.py) >>>"
END_MARKER = "# <<< end generated (backend) <<<"

# On first run (markers absent) the existing file is the hand-written version
# whose backend block must be dropped; only the frontend section below this
# header is preserved verbatim.
FRONTEND_HEADER = "# Frontend Configuration"

# Stable group ordering for output. Groups not listed are appended alphabetically.
GROUP_ORDER = [
    "Database",
    "App Settings",
    "AI Provider",
    "S3 / MinIO Storage",
    "Observability",
    "Security",
    "Feature Flags",
    "Deployment metadata",
    "Rate Limiting",
]


def _canonical_key(name: str, field) -> str:
    """Derive the canonical env key for a field."""
    from pydantic import AliasChoices

    alias = field.validation_alias
    if isinstance(alias, str):
        return alias
    if isinstance(alias, AliasChoices):
        # First choice is the canonical documentation key.
        return str(alias.choices[0])
    return name.upper()


def _render_value(value: object) -> str:
    """Render a value as it should appear after ``KEY=``."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float) and value.is_integer():
        # Avoid emitting ``360.0`` for an int-like timeout default.
        return str(int(value))
    return str(value)


def _shown_value(field) -> str:
    """The value to show in .env.example (json_schema_extra ``example`` wins)."""
    extra = field.json_schema_extra
    if isinstance(extra, dict) and "example" in extra:
        return str(extra["example"])
    return _render_value(field.default)


def collect_backend_fields() -> list[dict]:
    """Return env-field metadata dicts for every backend Settings env field.

    Only fields carrying a ``group`` in ``json_schema_extra`` are treated as env
    fields; ``cached_property`` helpers (cors_origins, fallback_models) are not
    ``model_fields`` and are therefore excluded automatically.
    """
    settings_cls = _settings_model()
    fields: list[dict] = []
    for name, field in settings_cls.model_fields.items():
        extra = field.json_schema_extra
        if not isinstance(extra, dict) or "group" not in extra:
            continue
        fields.append(
            {
                "field": name,
                "key": _canonical_key(name, field),
                "default": _render_value(field.default),
                "has_default": not field.is_required(),
                "value": _shown_value(field),
                "description": (field.description or "").strip(),
                "group": str(extra["group"]),
                "vault": bool(extra.get("vault", False)),
                "extra_keys": list(extra.get("extra_keys", [])),
            }
        )
    return fields


def _group_sort_key(group: str) -> tuple[int, str]:
    if group in GROUP_ORDER:
        return (GROUP_ORDER.index(group), "")
    return (len(GROUP_ORDER), group)


def render_backend_block(fields: list[dict]) -> str:
    """Render the managed backend block (between, but excluding, the markers)."""
    grouped: dict[str, list[dict]] = {}
    for field in fields:
        grouped.setdefault(field["group"], []).append(field)

    lines: list[str] = []
    for group in sorted(grouped, key=_group_sort_key):
        lines.append(f"# === {group} ===")
        for field in sorted(grouped[group], key=lambda f: f["key"]):
            comment = field["description"] or field["key"]
            if field["vault"]:
                comment = f"{comment} [VAULT]"
            lines.append(f"# {comment}")
            lines.append(f"{field['key']}={field['value']}")
            for extra_key in field["extra_keys"]:
                lines.append(f"{extra_key}={field['value']}")
        lines.append("")
    # Drop the trailing blank line produced by the last group.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines)


def render_env_example(existing: str | None, fields: list[dict]) -> str:
    """Return the full .env.example content with the managed region replaced."""
    block = render_backend_block(fields)
    managed = f"{BEGIN_MARKER}\n{block}\n{END_MARKER}"

    if existing and BEGIN_MARKER in existing and END_MARKER in existing:
        head, _, rest = existing.partition(BEGIN_MARKER)
        _, _, tail = rest.partition(END_MARKER)
        return f"{head}{managed}{tail}"

    # First run (or markers removed): insert the managed region at the very top
    # and preserve only the existing frontend section below it (the old
    # hand-written backend block is dropped, since it is now generated).
    if existing:
        lines = existing.splitlines()
        start = next(
            (i for i, line in enumerate(lines) if FRONTEND_HEADER in line),
            None,
        )
        if start is not None:
            # Include any banner comment lines directly above the header.
            while start > 0 and lines[start - 1].lstrip().startswith("#"):
                start -= 1
            frontend = "\n".join(lines[start:]).strip("\n")
            if frontend:
                return f"{managed}\n\n{frontend}\n"
    return f"{managed}\n"


def render_reference_doc(fields: list[dict]) -> str:
    """Render the markdown env-reference table."""
    rows = sorted(fields, key=lambda f: (_group_sort_key(f["group"]), f["key"]))
    lines = [
        "<!-- GENERATED by tools/generate_env_reference.py — do not edit. -->",
        "",
        "# Backend Environment Reference",
        "",
        "Generated from `apps/backend/src/config.py` (`Settings` pydantic metadata).",
        "Run `python tools/generate_env_reference.py` to regenerate.",
        "",
        "Where a field's `.env.example` value intentionally differs from its code "
        "default (local-dev convenience), both are shown.",
        "",
        "| Key | Default | Example | Vault | Group | Description |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for field in rows:
        default = field["default"]
        shown = field["value"]
        default_cell = f"`{default}`" if default else ""
        # Only surface an Example when it differs from the real default.
        example_cell = f"`{shown}`" if shown and shown != default else ""
        vault_cell = "yes" if field["vault"] else ""
        description = field["description"].replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| `{field['key']}` | {default_cell} | {example_cell} | {vault_cell} | {field['group']} | {description} |"
        )
        # Alias keys (json_schema_extra["extra_keys"]) are part of the accepted
        # env contract; list them so the reference is complete.
        for extra_key in field["extra_keys"]:
            lines.append(
                f"| `{extra_key}` |  |  | {vault_cell} | {field['group']} | Alias of `{field['key']}`. |"
            )
    lines.append("")
    return "\n".join(lines)


def render_required_env_manifest(fields: list[dict]) -> str:
    """Render the machine-readable required-env manifest (#1828, #876 boundary; #2005 v2).

    The manifest is the infra2-sdk environment contract (``contract_version`` 2): every
    entry carries the field's *source class* (who produces the value), ``empty_ok``,
    ``scope``, ``provided_by`` / ``composed_from``, and the v1 keys infra2's template check
    already reads (``env`` — named so no JSON line is shaped like a key/secret assignment,
    ``aliases``, ``vault``, ``has_default``). ``vault`` is the legacy alias of "the
    deployment must inject this"; it is preserved verbatim from ``config.py``.
    Deterministic ordering (by ``env``) so the artifact diffs cleanly.
    """
    import json

    contract = _environment_contract()
    vault_by_field = {field["field"]: field["vault"] for field in fields}
    entries = []
    for entry in sorted(contract.fields, key=lambda item: item.env):
        if entry.field not in vault_by_field:
            continue  # not an env field (no ``group``): mirrors collect_backend_fields
        data = entry.to_dict()
        data["vault"] = vault_by_field[entry.field]
        entries.append(data)
    manifest = {
        "contract_version": contract.contract_version,
        "generated_by": "tools/generate_env_reference.py — do not edit",
        "source": MANIFEST_SOURCE,
        "consumer": (
            "infra2 CI checks secrets.ctmpl against this manifest "
            "(wangzitian0/finance_report#1828 G-injection-drift-gate); infra2 derives the "
            "template, policy and reconciliation from the source classes (#2005)"
        ),
        "fields": entries,
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def _environment_contract():
    """The infra2-sdk v2 manifest: model metadata plus ``config.ENV_SOURCE_CLASSES``.

    The source classes live in a side table (see config.py) so that declaring one never
    edits a public ``Field()`` signature. infra2-sdk >= 1.5.0 folds that table itself
    (``overrides=``, keyed by field name): an unknown name raises ``ValueError`` and a
    ``release`` / ``decision`` override implies ``injected`` — the deployment, not the
    store, supplies it.
    """
    from infra2_sdk.runtime.config_schema import environment_manifest_from_model

    module = _settings_module()
    try:
        return environment_manifest_from_model(
            module.Settings,
            source=MANIFEST_SOURCE,
            overrides=getattr(module, "ENV_SOURCE_CLASSES", {}),
        )
    except ValueError as error:
        # keep the tool's output actionable: the SDK names the offending field(s)
        raise SystemExit(f"ENV_SOURCE_CLASSES: {error}") from None


def manifest_gate_errors() -> list[str]:
    """Offline contract violations (infra2_sdk.ci); no infrastructure involved."""
    from infra2_sdk.ci import validate_manifest_offline

    return validate_manifest_offline(_environment_contract())


def _diff(label: str, current: str, generated: str) -> str:
    return "".join(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=f"{label} (on disk)",
            tofile=f"{label} (generated)",
        )
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 (with a diff) if on-disk files differ from generated output.",
    )
    args = parser.parse_args(argv)

    fields = collect_backend_fields()

    existing_env = ENV_EXAMPLE_PATH.read_text() if ENV_EXAMPLE_PATH.exists() else None
    new_env = render_env_example(existing_env, fields)
    new_doc = render_reference_doc(fields)
    new_manifest = render_required_env_manifest(fields)

    if args.check:
        drift = False
        if existing_env != new_env:
            drift = True
            print(_diff(".env.example", existing_env or "", new_env))
        current_doc = (
            ENV_REFERENCE_DOC_PATH.read_text()
            if ENV_REFERENCE_DOC_PATH.exists()
            else ""
        )
        if current_doc != new_doc:
            drift = True
            print(_diff(str(ENV_REFERENCE_DOC_PATH.name), current_doc, new_doc))
        current_manifest = (
            REQUIRED_ENV_MANIFEST_PATH.read_text()
            if REQUIRED_ENV_MANIFEST_PATH.exists()
            else ""
        )
        if current_manifest != new_manifest:
            drift = True
            print(
                _diff(
                    str(REQUIRED_ENV_MANIFEST_PATH.name), current_manifest, new_manifest
                )
            )
        gate_errors = manifest_gate_errors()
        for error in gate_errors:
            print(f"manifest gate: {error}")
        if drift or gate_errors:
            print(
                "ERROR: generated env files are out of date or violate the manifest contract. "
                "Run: python tools/generate_env_reference.py",
                file=sys.stderr,
            )
            return 1
        print(
            "OK: .env.example, env-reference.generated.md and required-env.generated.json are up to date."
        )
        return 0

    ENV_EXAMPLE_PATH.write_text(new_env)
    ENV_REFERENCE_DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    ENV_REFERENCE_DOC_PATH.write_text(new_doc)
    REQUIRED_ENV_MANIFEST_PATH.write_text(new_manifest)
    print(f"Wrote {ENV_EXAMPLE_PATH.relative_to(ROOT_DIR)}")
    print(f"Wrote {ENV_REFERENCE_DOC_PATH.relative_to(ROOT_DIR)}")
    print(f"Wrote {REQUIRED_ENV_MANIFEST_PATH.relative_to(ROOT_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
