#!/usr/bin/env python3
"""Generate the backend env block of ``.env.example`` and an env-reference doc.

Infra-014 C3: the backend portion of ``.env.example`` and
``docs/ssot/env-reference.generated.md`` are generated directly from the
``Settings(BaseSettings)`` pydantic metadata in ``apps/backend/src/config.py``
(``description=`` and ``json_schema_extra={...}``) so they can never drift from
the code.

Only the backend block of ``.env.example`` is managed (delimited by sentinel
markers). The frontend block below the markers (``NEXT_PUBLIC_*``,
``OPENPANEL_*``) is preserved verbatim because those keys are not defined in
``config.py``.

Usage:
    python tools/generate_env_reference.py            # write files
    python tools/generate_env_reference.py --check    # exit 1 if files drift
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from pydantic import AliasChoices
from pydantic.fields import FieldInfo

ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "apps" / "backend"

# Make ``from src.config import Settings`` importable.
for _path in (str(BACKEND_DIR), str(BACKEND_DIR / "src")):
    if _path not in sys.path:
        sys.path.insert(0, _path)

from src.config import Settings  # noqa: E402

ENV_EXAMPLE_PATH = ROOT_DIR / ".env.example"
ENV_REFERENCE_DOC_PATH = ROOT_DIR / "docs" / "ssot" / "env-reference.generated.md"

BEGIN_MARKER = (
    "# >>> generated by tools/generate_env_reference.py — do not edit "
    "(backend, from config.py) >>>"
)
END_MARKER = "# <<< end generated (backend) <<<"

# On first run (markers absent) the existing file is the hand-written version
# whose backend block must be dropped; only the frontend section below this
# header is preserved verbatim.
FRONTEND_HEADER = "# Frontend Configuration"

# Stable group ordering for output. Groups not listed are appended alphabetically.
GROUP_ORDER = [
    "Database",
    "App Settings",
    "AI Provider",
    "S3 / MinIO Storage",
    "Observability",
    "Security",
    "Feature Flags",
    "Deployment metadata",
    "Rate Limiting",
]


def _canonical_key(name: str, field: FieldInfo) -> str:
    """Derive the canonical env key for a field."""
    alias = field.validation_alias
    if isinstance(alias, str):
        return alias
    if isinstance(alias, AliasChoices):
        # First choice is the canonical documentation key.
        return str(alias.choices[0])
    return name.upper()


def _render_value(value: object) -> str:
    """Render a value as it should appear after ``KEY=``."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float) and value.is_integer():
        # Avoid emitting ``360.0`` for an int-like timeout default.
        return str(int(value))
    return str(value)


def _shown_value(field: FieldInfo) -> str:
    """The value to show in .env.example (json_schema_extra ``example`` wins)."""
    extra = field.json_schema_extra
    if isinstance(extra, dict) and "example" in extra:
        return str(extra["example"])
    return _render_value(field.default)


def collect_backend_fields() -> list[dict]:
    """Return env-field metadata dicts for every backend Settings env field.

    Only fields carrying a ``group`` in ``json_schema_extra`` are treated as env
    fields; ``cached_property`` helpers (cors_origins, fallback_models) are not
    ``model_fields`` and are therefore excluded automatically.
    """
    fields: list[dict] = []
    for name, field in Settings.model_fields.items():
        extra = field.json_schema_extra
        if not isinstance(extra, dict) or "group" not in extra:
            continue
        fields.append(
            {
                "key": _canonical_key(name, field),
                "value": _shown_value(field),
                "description": (field.description or "").strip(),
                "group": str(extra["group"]),
                "vault": bool(extra.get("vault", False)),
                "extra_keys": list(extra.get("extra_keys", [])),
            }
        )
    return fields


def _group_sort_key(group: str) -> tuple[int, str]:
    if group in GROUP_ORDER:
        return (GROUP_ORDER.index(group), "")
    return (len(GROUP_ORDER), group)


def render_backend_block(fields: list[dict]) -> str:
    """Render the managed backend block (between, but excluding, the markers)."""
    grouped: dict[str, list[dict]] = {}
    for field in fields:
        grouped.setdefault(field["group"], []).append(field)

    lines: list[str] = []
    for group in sorted(grouped, key=_group_sort_key):
        lines.append(f"# === {group} ===")
        for field in sorted(grouped[group], key=lambda f: f["key"]):
            comment = field["description"] or field["key"]
            if field["vault"]:
                comment = f"{comment} [VAULT]"
            lines.append(f"# {comment}")
            lines.append(f"{field['key']}={field['value']}")
            for extra_key in field["extra_keys"]:
                lines.append(f"{extra_key}={field['value']}")
        lines.append("")
    # Drop the trailing blank line produced by the last group.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines)


def render_env_example(existing: str | None, fields: list[dict]) -> str:
    """Return the full .env.example content with the managed region replaced."""
    block = render_backend_block(fields)
    managed = f"{BEGIN_MARKER}\n{block}\n{END_MARKER}"

    if existing and BEGIN_MARKER in existing and END_MARKER in existing:
        head, _, rest = existing.partition(BEGIN_MARKER)
        _, _, tail = rest.partition(END_MARKER)
        return f"{head}{managed}{tail}"

    # First run (or markers removed): insert the managed region at the very top
    # and preserve only the existing frontend section below it (the old
    # hand-written backend block is dropped, since it is now generated).
    if existing:
        lines = existing.splitlines()
        start = next(
            (i for i, line in enumerate(lines) if FRONTEND_HEADER in line),
            None,
        )
        if start is not None:
            # Include any banner comment lines directly above the header.
            while start > 0 and lines[start - 1].lstrip().startswith("#"):
                start -= 1
            frontend = "\n".join(lines[start:]).strip("\n")
            if frontend:
                return f"{managed}\n\n{frontend}\n"
    return f"{managed}\n"


def render_reference_doc(fields: list[dict]) -> str:
    """Render the markdown env-reference table."""
    rows = sorted(fields, key=lambda f: (_group_sort_key(f["group"]), f["key"]))
    lines = [
        "<!-- GENERATED by tools/generate_env_reference.py — do not edit. -->",
        "",
        "# Backend Environment Reference",
        "",
        "Generated from `apps/backend/src/config.py` (`Settings` pydantic metadata).",
        "Run `python tools/generate_env_reference.py` to regenerate.",
        "",
        "| Key | Default | Vault | Group | Description |",
        "| --- | --- | --- | --- | --- |",
    ]
    for field in rows:
        default = field["value"]
        default_cell = f"`{default}`" if default else ""
        vault_cell = "yes" if field["vault"] else ""
        description = field["description"].replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| `{field['key']}` | {default_cell} | {vault_cell} | "
            f"{field['group']} | {description} |"
        )
    lines.append("")
    return "\n".join(lines)


def _diff(label: str, current: str, generated: str) -> str:
    return "".join(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=f"{label} (on disk)",
            tofile=f"{label} (generated)",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 (with a diff) if on-disk files differ from generated output.",
    )
    args = parser.parse_args()

    fields = collect_backend_fields()

    existing_env = (
        ENV_EXAMPLE_PATH.read_text() if ENV_EXAMPLE_PATH.exists() else None
    )
    new_env = render_env_example(existing_env, fields)
    new_doc = render_reference_doc(fields)

    if args.check:
        drift = False
        if existing_env != new_env:
            drift = True
            print(_diff(".env.example", existing_env or "", new_env))
        current_doc = (
            ENV_REFERENCE_DOC_PATH.read_text()
            if ENV_REFERENCE_DOC_PATH.exists()
            else ""
        )
        if current_doc != new_doc:
            drift = True
            print(_diff(str(ENV_REFERENCE_DOC_PATH.name), current_doc, new_doc))
        if drift:
            print(
                "ERROR: generated env files are out of date. "
                "Run: python tools/generate_env_reference.py",
                file=sys.stderr,
            )
            return 1
        print("OK: .env.example and env-reference.generated.md are up to date.")
        return 0

    ENV_EXAMPLE_PATH.write_text(new_env)
    ENV_REFERENCE_DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    ENV_REFERENCE_DOC_PATH.write_text(new_doc)
    print(f"Wrote {ENV_EXAMPLE_PATH.relative_to(ROOT_DIR)}")
    print(f"Wrote {ENV_REFERENCE_DOC_PATH.relative_to(ROOT_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
